
var disable_empty_list=true;

addListGroup("taxons", "taxon-phylums");

addOption("taxon-phylums", "Select Phylum", "None", "None");
addList("taxon-phylums", "Cnidaria", "Cnidaria", "Cnidaria");
addList("taxon-phylums", "Porifera", "Porifera", "Porifera");
addList("taxon-phylums", "NA", "NA", "NA");

addOption("NA", "Select Order", "None", "None", 1); 

addOption("Cnidaria", "Select Order", "None", "None", 1); 
//addList("Cnidaria", "Actiniaria", "Actiniaria", "Actiniaria");
addList("Cnidaria", "Alcyonacea", "Alcyonacea", "Alcyonacea");
addList("Cnidaria", "Anthoathecata", "Anthoathecata", "Anthoathecata");
addList("Cnidaria", "Antipatharia", "Antipatharia", "Antipatharia");
//addList("Cnidaria", "Corallimorpharia", "Corallimorpharia", "Corallimorpharia");
//addList("Cnidaria", "Coronatae", "Coronatae", "Coronatae");
addList("Cnidaria", "Gorgonacea", "Gorgonacea", "Gorgonacea");
addList("Cnidaria", "Helioporacea", "Helioporacea", "Helioporacea");
addList("Cnidaria", "Leptothecata", "Leptothecata", "Leptothecata");
//addList("Cnidaria", "Narcomedusae", "Narcomedusae", "Narcomedusae");
addList("Cnidaria", "Pennatulacea", "Pennatulacea", "Pennatulacea");
addList("Cnidaria", "Scleractinia", "Scleractinia", "Scleractinia");
//addList("Cnidaria", "Siphonophorae", "Siphonophorae", "Siphonophorae");
addList("Cnidaria", "Zoantharia", "Zoantharia", "Zoantharia");

//addOption("Actiniaria", "Select Family", "None", "None", 1);
//addList("Actiniaria", "Actinernidae", "Actinernidae", "Actiniaria-Actinernidae");
//addList("Actiniaria", "Actinoscyphiidae", "Actinoscyphiidae", "Actiniaria-Actinoscyphiidae");
//addList("Actiniaria", "Actinostolidae", "Actinostolidae", "Actiniaria-Actinostolidae");
//addList("Actiniaria", "Edwardsiidae", "Edwardsiidae", "Actiniaria-Edwardsiidae");
//addList("Actiniaria", "Hormathiidae", "Hormathiidae", "Actiniaria-Hormathiidae");
//addList("Actiniaria", "Liponematidae", "Liponematidae", "Actiniaria-Liponematidae");
//addList("Actiniaria", "Spongiactinidae", "Spongiactinidae", "Actiniaria-Spongiactinidae");
//addList("Actiniaria", "NA", "NA", "Actiniaria-NA");
//addOption("Actiniaria-Actinernidae", "Select Genus", "None");
//addOption("Actiniaria-Actinernidae", "Actinernus", "Actinernus");
//addOption("Actiniaria-Actinoscyphiidae", "Select Genus", "None");
//addOption("Actiniaria-Actinoscyphiidae", "Actinoscyphia", "Actinoscyphia");
//addOption("Actiniaria-Actinostolidae", "Select Genus", "None");
//addOption("Actiniaria-Actinostolidae", "NA", "NA");
//addOption("Actiniaria-Edwardsiidae", "Select Genus", "None");
//addOption("Actiniaria-Edwardsiidae", "NA", "NA");
//addOption("Actiniaria-Hormathiidae", "Select Genus", "None");
//addOption("Actiniaria-Hormathiidae", "Amphianthus", "Amphianthus");
//addOption("Actiniaria-Hormathiidae", "Phelliactis", "Phelliactis");
//addOption("Actiniaria-Hormathiidae", "NA", "NA");
//addOption("Actiniaria-Liponematidae", "Select Genus", "None");
//addOption("Actiniaria-Liponematidae", "Liponema", "Liponema");
//addOption("Actiniaria-Spongiactinidae", "Select Genus", "None");
//addOption("Actiniaria-Spongiactinidae", "Spongiactis", "Spongiactis");

addOption("Alcyonacea", "Select Family", "None", "None", 1);
addList("Alcyonacea", "Alcyoniidae", "Alcyoniidae", "Alcyonacea-Alcyoniidae");
addList("Alcyonacea", "Aquaumbridae", "Aquaumbridae", "Alcyonacea-Aquaumbridae");
addList("Alcyonacea", "Briareidae", "Briareidae", "Alcyonacea-Briareidae");
addList("Alcyonacea", "Clavulariidae", "Clavulariidae", "Alcyonacea-Clavulariidae");
addList("Alcyonacea", "Isididae", "Isididae", "Alcyonacea-Isididae");
addList("Alcyonacea", "Nephtheidae", "Nephtheidae", "Alcyonacea-Nephtheidae");
addList("Alcyonacea", "Nidaliidae", "Nidaliidae", "Alcyonacea-Nidaliidae");
addList("Alcyonacea", "Paralcyoniidae", "Paralcyoniidae", "Alcyonacea-Paralcyoniidae");
//addList("Alcyonacea", "Tubiporidae", "Tubiporidae", "Alcyonacea-Tubiporidae");
addList("Alcyonacea", "Xeniidae", "Xeniidae", "Alcyonacea-Xeniidae");
addList("Alcyonacea", "NA", "NA", "Alcyonacea-NA");
addOption("Alcyonacea-Alcyoniidae", "Select Genus", "None");
addOption("Alcyonacea-Alcyoniidae", "Alcyonium", "Alcyonium");
addOption("Alcyonacea-Alcyoniidae", "Anthomastus","Anthomastus");
addOption("Alcyonacea-Alcyoniidae", "Bathyalcyon","Bathyalcyon");
addOption("Alcyonacea-Alcyoniidae", "Bellonella", "Bellonella");
//addOption("Alcyonacea-Alcyoniidae", "Discophyton", "Discophyton");
addOption("Alcyonacea-Alcyoniidae", "Duva", "Duva");
addOption("Alcyonacea-Alcyoniidae", "Eleutherobia", "Eleutherobia");
addOption("Alcyonacea-Alcyoniidae", "Heteropolypus", "Heteropolypus");
addOption("Alcyonacea-Alcyoniidae", "Protodendron", "Protodendron");
addOption("Alcyonacea-Alcyoniidae", "Pseudoanthomastus", "Pseudoanthomastus");
addOption("Alcyonacea-Alcyoniidae", "Sarcophyton", "Sarcophyton");
addOption("Alcyonacea-Alcyoniidae", "Sinularia", "Sinularia");
//addOption("Alcyonacea-Alcyoniidae", "Thrombophyton", "Thrombophyton");
addOption("Alcyonacea-Alcyoniidae", "NA", "NA");
addOption("Alcyonacea-Aquaumbridae", "Select Genus", "None");
addOption("Alcyonacea-Aquaumbridae", "NA", "NA");
addOption("Alcyonacea-Briareidae", "Select Genus", "None");
addOption("Alcyonacea-Briareidae", "Briareum", "Briareum");
addOption("Alcyonacea-Clavulariidae", "Select Genus", "None");
addOption("Alcyonacea-Clavulariidae", "Carijoa","Carijoa");
addOption("Alcyonacea-Clavulariidae", "Clavularia","Clavularia");
//addOption("Alcyonacea-Clavulariidae", "Cryptophyton","Cryptophyton");
addOption("Alcyonacea-Clavulariidae", "Pseudocladochonus","Pseudocladochonus");
addOption("Alcyonacea-Clavulariidae", "Sarcodictyon","Sarcodictyon");
addOption("Alcyonacea-Clavulariidae", "Scleranthelia","Scleranthelia");
addOption("Alcyonacea-Clavulariidae", "Stereotelesto","Stereotelesto");
addOption("Alcyonacea-Clavulariidae", "Telesto","Telesto");
addOption("Alcyonacea-Clavulariidae", "Telestula", "Telestula");
addOption("Alcyonacea-Clavulariidae", "NA", "NA");
addOption("Alcyonacea-Isididae", "Select Genus", "None");
addOption("Alcyonacea-Isididae", "Lepidisis","Lepidisis");
addOption("Alcyonacea-Isididae", "Stenisis","Stenisis");
addOption("Alcyonacea-Nephtheidae", "Select Genus", "None");
addOption("Alcyonacea-Nephtheidae", "Capnella","Capnella");
addOption("Alcyonacea-Nephtheidae", "Chromonephthea", "Chromonephthea");
addOption("Alcyonacea-Nephtheidae", "Dendronephthya", "Dendronephthya");
addOption("Alcyonacea-Nephtheidae", "Drifa", "Drifa");
addOption("Alcyonacea-Nephtheidae", "Duva", "Duva");
//addOption("Alcyonacea-Nephtheidae", "Eunephthya", "Eunephthya");
addOption("Alcyonacea-Nephtheidae", "Gersemia", "Gersemia");
addOption("Alcyonacea-Nephtheidae", "Lithophytum", "Lithophytum");
addOption("Alcyonacea-Nephtheidae", "Litophyton", "Litophyton");
addOption("Alcyonacea-Nephtheidae", "Neospongodes", "Neospongodes");
addOption("Alcyonacea-Nephtheidae", "Pseudodrifa", "Pseudodrifa");
addOption("Alcyonacea-Nephtheidae", "Scleronephthya cf.", "Scleronephthya cf.");
addOption("Alcyonacea-Nephtheidae", "Stereonephthya", "Stereonephthya");
addOption("Alcyonacea-Nephtheidae", "NA", "NA");
addOption("Alcyonacea-Nidaliidae", "Select Genus", "None");
addOption("Alcyonacea-Nidaliidae", "Chironephthya", "Chironephthya");
addOption("Alcyonacea-Nidaliidae", "Nidalia", "Nidalia");
addOption("Alcyonacea-Nidaliidae", "Siphonogorgia", "Siphonogorgia");
addOption("Alcyonacea-Nidaliidae", "NA", "NA");
addOption("Alcyonacea-Paralcyoniidae", "Select Genus", "None");
addOption("Alcyonacea-Paralcyoniidae", "Paralcyonium", "Paralcyonium");
//addOption("Alcyonacea-Tubiporidae", "Select Genus", "None");
//addOption("Alcyonacea-Tubiporidae", "Tubipora", "Tubipora");
addOption("Alcyonacea-Xeniidae", "Select Genus", "None");
addOption("Alcyonacea-Xeniidae", "Anthelia", "Anthelia");
addOption("Alcyonacea-Xeniidae", "Sympodium", "Sympodium");

addOption("Anthoathecata", "Select Family", "None", "None", 1);
//addList("Anthoathecata", "Corymorphidae", "Corymorphidae", "Anthoathecata-Corymorphidae");
//addList("Anthoathecata", "Milleporidae", "Milleporidae", "Anthoathecata-Milleporidae");
addList("Anthoathecata", "Solanderiidae", "Solanderiidae", "Anthoathecata-Solanderiidae");
addList("Anthoathecata", "Stylasteridae", "Stylasteridae", "Anthoathecata-Stylasteridae");
//addList("Anthoathecata", "Tubulariidae", "Tubulariidae", "Anthoathecata-Tubulariidae");
//addList("Anthoathecata", "NA", "NA", "Anthoathecata-NA");
//addOption("Anthoathecata-Corymorphidae", "Select Genus", "None");
//addOption("Anthoathecata-Corymorphidae", "NA", "NA");
//addOption("Anthoathecata-Milleporidae", "Select Genus", "None");
//addOption("Anthoathecata-Milleporidae", "Millepora", "Millepora");
addOption("Anthoathecata-Solanderiidae", "Select Genus", "None");
addOption("Anthoathecata-Solanderiidae", "Solanderia", "Solanderia");
addOption("Anthoathecata-Stylasteridae", "Select Genus", "None");
addOption("Anthoathecata-Stylasteridae", "Adelopora", "Adelopora");
addOption("Anthoathecata-Stylasteridae", "Astya", "Astya");
addOption("Anthoathecata-Stylasteridae", "Calyptopor", "Calyptopor");
addOption("Anthoathecata-Stylasteridae", "Cheiloporidion", "Cheiloporidion");
addOption("Anthoathecata-Stylasteridae", "Conopora", "Conopora");
addOption("Anthoathecata-Stylasteridae", "Crypthelia", "Crypthelia");
addOption("Anthoathecata-Stylasteridae", "Cyclohelia", "Cyclohelia");
addOption("Anthoathecata-Stylasteridae", "Distichopora", "Distichopora");
addOption("Anthoathecata-Stylasteridae", "Errina", "Errina");
addOption("Anthoathecata-Stylasteridae", "Errinopora", "Errinopora");
addOption("Anthoathecata-Stylasteridae", "Errinopsis", "Errinopsis");
addOption("Anthoathecata-Stylasteridae", "Inferiolabiata", "Inferiolabiata");
addOption("Anthoathecata-Stylasteridae", "Lepidopora", "Lepidopora");
addOption("Anthoathecata-Stylasteridae", "Lepidotheca", "Lepidotheca");
addOption("Anthoathecata-Stylasteridae", "Leptohelia", "Leptohelia");
addOption("Anthoathecata-Stylasteridae", "Paraconopora", "Paraconopora");
addOption("Anthoathecata-Stylasteridae", "Paraerrina", "Paraerrina");
addOption("Anthoathecata-Stylasteridae", "Phalangopora", "Phalangopora");
addOption("Anthoathecata-Stylasteridae", "Pliobothrus", "Pliobothrus");
addOption("Anthoathecata-Stylasteridae", "Pseudocrypthelia", "Pseudocrypthelia");
addOption("Anthoathecata-Stylasteridae", "Sporadopora", "Sporadopora");
addOption("Anthoathecata-Stylasteridae", "Stellapora", "Stellapora");
addOption("Anthoathecata-Stylasteridae", "Stenohelia", "Stenohelia");
addOption("Anthoathecata-Stylasteridae", "Stephanohelia", "Stephanohelia");
addOption("Anthoathecata-Stylasteridae", "Stylantheca", "Stylantheca");
addOption("Anthoathecata-Stylasteridae", "Stylaster", "Stylaster");
addOption("Anthoathecata-Stylasteridae", "Systemapora", "Systemapora");
addOption("Anthoathecata-Stylasteridae", "NA", "NA");
//addOption("Anthoathecata-Tubulariidae", "Select Genus", "None");
//addOption("Anthoathecata-Tubulariidae", "NA", "NA");

addOption("Antipatharia", "Select Family", "None", "None", 1);
addList("Antipatharia", "Antipathidae", "Antipathidae", "Antipatharia-Antipathidae");
addList("Antipatharia", "Aphanipathidae", "Aphanipathidae", "Antipatharia-Aphanipathidae");
addList("Antipatharia", "Cladopathidae", "Cladopathidae", "Antipatharia-Cladopathidae");
addList("Antipatharia", "Leiopathidae", "Leiopathidae", "Antipatharia-Leiopathidae");
addList("Antipatharia", "Myriopathidae", "Myriopathidae", "Antipatharia-Myriopathidae");
addList("Antipatharia", "Schizopathidae", "Schizopathidae", "Antipatharia-Schizopathidae");
addList("Antipatharia", "Stylopathidae", "Stylopathidae", "Antipatharia-Stylopathidae");
addList("Antipatharia", "NA", "NA", "Antipatharia-NA");
addOption("Antipatharia-Antipathidae", "Select Genus", "None");
addOption("Antipatharia-Antipathidae", "Allopathes","Allopathes");
addOption("Antipatharia-Antipathidae", "Antipathes","Antipathes");
addOption("Antipatharia-Antipathidae", "Arachnopathes","Arachnopathes");
addOption("Antipatharia-Antipathidae", "Cirrhipathes", "Cirrhipathes");
addOption("Antipatharia-Antipathidae", "Elatopathes", "Elatopathes");
addOption("Antipatharia-Antipathidae", "Plumapathes", "Plumapathes");
addOption("Antipatharia-Antipathidae", "Pseudocirrhipathes","Pseudocirrhipathes");
addOption("Antipatharia-Antipathidae", "Pteropathes","Pteropathes");
addOption("Antipatharia-Antipathidae", "Stichopathes", "Stichopathes");
addOption("Antipatharia-Antipathidae", "NA", "NA");
addOption("Antipatharia-Aphanipathidae", "Select Genus", "None");
addOption("Antipatharia-Aphanipathidae", "Acanthopathes", "Acanthopathes");
addOption("Antipatharia-Aphanipathidae", "Aphanipathes", "Aphanipathes");
addOption("Antipatharia-Aphanipathidae", "Asteriopathes", "Asteriopathes");
addOption("Antipatharia-Aphanipathidae", "Distichopathes", "Distichopathes");
addOption("Antipatharia-Aphanipathidae", "Elatopathes", "Elatopathes");
addOption("Antipatharia-Aphanipathidae", "Phanopathes", "Phanopathes"); 
addOption("Antipatharia-Aphanipathidae", "Pteridopathes", "Pteridopathes"); 
addOption("Antipatharia-Aphanipathidae", "Rhipidipathes", "Rhipidipathes");
addOption("Antipatharia-Aphanipathidae", "Tetrapathes", "Tetrapathes");
addOption("Antipatharia-Aphanipathidae", "NA", "NA");
addOption("Antipatharia-Cladopathidae", "Select Genus", "None");
addOption("Antipatharia-Cladopathidae", "Chrysopathes", "Chrysopathes");
addOption("Antipatharia-Cladopathidae", "Cladopathes", "Cladopathes");
addOption("Antipatharia-Cladopathidae", "Heteropathes", "Heteropathes");
addOption("Antipatharia-Cladopathidae", "Hexapathes", "Hexapathes");
addOption("Antipatharia-Cladopathidae", "Sibopathes", "Sibopathes");
addOption("Antipatharia-Cladopathidae", "Trissopathes", "Trissopathes");
addOption("Antipatharia-Cladopathidae", "NA", "NA");
addOption("Antipatharia-Leiopathidae", "Select Genus", "None");
addOption("Antipatharia-Leiopathidae", "Leiopathes", "Leiopathes");
addOption("Antipatharia-Leiopathidae", "NA", "NA");
addOption("Antipatharia-Myriopathidae", "Select Genus", "None");
addOption("Antipatharia-Myriopathidae", "Antipathella", "Antipathella");
addOption("Antipatharia-Myriopathidae", "Cupressopathes", "Cupressopathes");
addOption("Antipatharia-Myriopathidae", "Myriopathes", "Myriopathes");
addOption("Antipatharia-Myriopathidae", "Plumapathes", "Plumapathes");
addOption("Antipatharia-Myriopathidae", "Tanacetipathes", "Tanacetipathes");
addOption("Antipatharia-Myriopathidae", "NA", "NA");
addOption("Antipatharia-Schizopathidae", "Select Genus", "None");
addOption("Antipatharia-Schizopathidae", "Abyssopathes", "Abyssopathes");
addOption("Antipatharia-Schizopathidae", "Alternatipathes", "Alternatipathes");
addOption("Antipatharia-Schizopathidae", "Bathypathes", "Bathypathes");
addOption("Antipatharia-Schizopathidae", "Dendrobathypathes", "Dendrobathypathes");
addOption("Antipatharia-Schizopathidae", "Dendropathes", "Dendropathes");
addOption("Antipatharia-Schizopathidae", "Lillipathes", "Lillipathes");
addOption("Antipatharia-Schizopathidae", "Parantipathes", "Parantipathes");
addOption("Antipatharia-Schizopathidae", "Saropathes", "Saropathes");
addOption("Antipatharia-Schizopathidae", "Schizopathes", "Schizopathes");
addOption("Antipatharia-Schizopathidae", "Stauropathes", "Stauropathes");
addOption("Antipatharia-Schizopathidae", "Taxipathes", "Taxipathes");
addOption("Antipatharia-Schizopathidae", "Telopathes", "Telopathes");
addOption("Antipatharia-Schizopathidae", "Umbellapathes", "Umbellapathes");
addOption("Antipatharia-Schizopathidae", "NA", "NA");
addOption("Antipatharia-Stylopathidae", "Select Genus", "None");
addOption("Antipatharia-Stylopathidae", "Stylopathes", "Stylopathes");
addOption("Antipatharia-Stylopathidae", "Triadopathes", "Triadopathes");
addOption("Antipatharia-Stylopathidae", "Tylopathes", "Tylopathes");

//addOption("Corallimorpharia", "Select Family", "None", "None", 1);
//addList("Corallimorpharia", "Corallimorphidae", "Corallimorphidae", "Corallimorpharia-Corallimorphidae");
//addOption("Corallimorpharia-Corallimorphidae", "Select Genus", "None");
//addOption("Corallimorpharia-Corallimorphidae", "Cf. corallimorphus", "Cf. corallimorphus");

//addOption("Coronatae", "Select Family", "None", "None", 1);
//addList("Coronatae", "NA", "NA", "Coronatae-NA");

addOption("Gorgonacea", "Select Family", "None", "None", 1);
addList("Gorgonacea", "Acanthogorgiidae", "Acanthogorgiidae", "Gorgonacea-Acanthogorgiidae");
addList("Gorgonacea", "Anthothelidae", "Anthothelidae", "Gorgonacea-Anthothelidae");
addList("Gorgonacea", "Briareidae", "Briareidae", "Gorgonacea-Briareidae");
addList("Gorgonacea", "Chrysogorgiidae", "Chrysogorgiidae", "Gorgonacea-Chrysogorgiidae");
addList("Gorgonacea", "Clavulariidae", "Clavulariidae", "Gorgonacea-Clavulariidae");
addList("Gorgonacea", "Coralliidae", "Coralliidae", "Gorgonacea-Coralliidae");
addList("Gorgonacea", "Dendrobrachiidae", "Dendrobrachiidae", "Gorgonacea-Dendrobrachiidae");
addList("Gorgonacea", "Ellisellidae", "Ellisellidae", "Gorgonacea-Ellisellidae");
addList("Gorgonacea", "Gorgoniidae", "Gorgoniidae", "Gorgonacea-Gorgoniidae");
addList("Gorgonacea", "Isididae", "Isididae", "Gorgonacea-Isididae");
addList("Gorgonacea", "Keroeididae", "Keroeididae", "Gorgonacea-Keroeididae");
addList("Gorgonacea", "Melithaeidae", "Melithaeidae", "Gorgonacea-Melithaeidae");
addList("Gorgonacea", "Paragorgiidae", "Paragorgiidae", "Gorgonacea-Paragorgiidae");
addList("Gorgonacea", "Paramuriceidae", "Paramuriceidae", "Gorgonacea-Paramuriceidae");
addList("Gorgonacea", "Parisididae", "Parisididae", "Gorgonacea-Parisididae");
addList("Gorgonacea", "Plexauridae", "Plexauridae", "Gorgonacea-Plexauridae");
addList("Gorgonacea", "Primnoidae", "Primnoidae", "Gorgonacea-Primnoidae");
addList("Gorgonacea", "Spongiodermidae", "Spongiodermidae", "Gorgonacea-Spongiodermidae");
addList("Gorgonacea", "Subergorgiidae", "Subergorgiidae", "Gorgonacea-Subergorgiidae");
addList("Gorgonacea", "NA", "NA", "Gorgonacea-NA");
addOption("Gorgonacea-Acanthogorgiidae", "Select Genus", "None");
addOption("Gorgonacea-Acanthogorgiidae", "Acanthogorgia", "Acanthogorgia");
addOption("Gorgonacea-Acanthogorgiidae", "Anthogorgia", "Anthogorgia");
addOption("Gorgonacea-Acanthogorgiidae", "Calcigorgia", "Calcigorgia");
addOption("Gorgonacea-Acanthogorgiidae", "Calicogorgia", "Calicogorgia");
addOption("Gorgonacea-Acanthogorgiidae", "Cyclomuricea", "Cyclomuricea");
addOption("Gorgonacea-Acanthogorgiidae", "Muricella", "Muricella");
addOption("Gorgonacea-Acanthogorgiidae", "Versluysia", "Versluysia");
addOption("Gorgonacea-Acanthogorgiidae", "NA", "NA");
addOption("Gorgonacea-Anthothelidae", "Select Genus", "None");
addOption("Gorgonacea-Anthothelidae", "Anthothela", "Anthothela");
addOption("Gorgonacea-Anthothelidae", "Briareopsis", "Briareopsis");
addOption("Gorgonacea-Anthothelidae", "Diodogorgia", "Diodogorgia");
addOption("Gorgonacea-Anthothelidae", "Erythropodium", "Erythropodium");
addOption("Gorgonacea-Anthothelidae", "Iciligorgia", "Iciligorgia");
addOption("Gorgonacea-Anthothelidae", "Solenocaulon", "Solenocaulon");
addOption("Gorgonacea-Anthothelidae", "Victorgorgia", "Victorgorgia");
addOption("Gorgonacea-Anthothelidae", "NA", "NA");
addOption("Gorgonacea-Briareidae", "Select Genus", "None");
addOption("Gorgonacea-Briareidae", "Briareum", "Briareum");
addOption("Gorgonacea-Briareidae", "NA", "NA");
addOption("Gorgonacea-Chrysogorgiidae", "Select Genus", "None");
addOption("Gorgonacea-Chrysogorgiidae", "Chrysogorgia", "Chrysogorgia");
addOption("Gorgonacea-Chrysogorgiidae", "Distichogorgia", "Distichogorgia");
addOption("Gorgonacea-Chrysogorgiidae", "Flagelligorgia", "Flagelligorgia");
addOption("Gorgonacea-Chrysogorgiidae", "Helicogorgia", "Helicogorgia");
addOption("Gorgonacea-Chrysogorgiidae", "Iridogorgia", "Iridogorgia");
addOption("Gorgonacea-Chrysogorgiidae", "Metallogorgia", "Metallogorgia");
addOption("Gorgonacea-Chrysogorgiidae", "Pleurogorgia", "Pleurogorgia");
addOption("Gorgonacea-Chrysogorgiidae", "Radicipes", "Radicipes");
addOption("Gorgonacea-Chrysogorgiidae", "Rhodaniridogorgia", "Rhodaniridogorgia");
addOption("Gorgonacea-Chrysogorgiidae", "Stephanogorgia", "Stephanogorgia");
addOption("Gorgonacea-Chrysogorgiidae", "Trichogorgia", "Trichogorgia");
addOption("Gorgonacea-Chrysogorgiidae", "Xenogorgia", "Xenogorgia");
addOption("Gorgonacea-Chrysogorgiidae", "NA", "NA");
addOption("Gorgonacea-Clavulariidae", "Select Genus", "None");
addOption("Gorgonacea-Clavulariidae", "Clavularia", "Clavularia");
addOption("Gorgonacea-Coralliidae", "Select Genus", "None");
addOption("Gorgonacea-Coralliidae", "Corallium", "Corallium");
addOption("Gorgonacea-Coralliidae", "Hemicorallium", "Hemicorallium");
addOption("Gorgonacea-Coralliidae", "Paracorallium", "Paracorallium");
addOption("Gorgonacea-Coralliidae", "NA", "NA");
addOption("Gorgonacea-Dendrobrachiidae", "Select Genus", "None");
addOption("Gorgonacea-Dendrobrachiidae", "Dendrobrachia", "Dendrobrachia");
addOption("Gorgonacea-Ellisellidae", "Select Genus", "None");
//addOption("Gorgonacea-Ellisellidae", "Ctenocella", "Ctenocella");
//addOption("Gorgonacea-Ellisellidae", "Dichotella", "Dichotella");
addOption("Gorgonacea-Ellisellidae", "Ellisella", "Ellisella");
//addOption("Gorgonacea-Ellisellidae", "Heliania", "Heliania");
addOption("Gorgonacea-Ellisellidae", "Junceella", "Junceella");
addOption("Gorgonacea-Ellisellidae", "Nicella", "Nicella");
addOption("Gorgonacea-Ellisellidae", "Riisea", "Riisea");
addOption("Gorgonacea-Ellisellidae", "Verrucella", "Verrucella");
addOption("Gorgonacea-Ellisellidae", "Viminella", "Viminella");
addOption("Gorgonacea-Ellisellidae", "NA", "NA");
addOption("Gorgonacea-Gorgoniidae", "Select Genus", "None");
addOption("Gorgonacea-Gorgoniidae", "Adelogorgia", "Adelogorgia");
addOption("Gorgonacea-Gorgoniidae", "Antillogorgia", "Antillogorgia");
addOption("Gorgonacea-Gorgoniidae", "Calcigorgia", "Calcigorgia");
addOption("Gorgonacea-Gorgoniidae", "Chromoplexaura", "Chromoplexaura");
addOption("Gorgonacea-Gorgoniidae", "Eugorgia", "Eugorgia");
addOption("Gorgonacea-Gorgoniidae", "Eunicella", "Eunicella");
addOption("Gorgonacea-Gorgoniidae", "Gorgonia", "Gorgonia");
addOption("Gorgonacea-Gorgoniidae", "Leptogorgia", "Leptogorgia");
addOption("Gorgonacea-Gorgoniidae", "Olindagorgia", "Olindagorgia");
addOption("Gorgonacea-Gorgoniidae", "Pacifigorgia", "Pacifigorgia");
addOption("Gorgonacea-Gorgoniidae", "Phyllogorgia", "Phyllogorgia");
addOption("Gorgonacea-Gorgoniidae", "Pseudopterogorgia", "Pseudopterogorgia");
addOption("Gorgonacea-Gorgoniidae", "Pterogorgia", "Pterogorgia");
addOption("Gorgonacea-Gorgoniidae", "NA", "NA");
addOption("Gorgonacea-Isididae", "Select Genus", "None");
addOption("Gorgonacea-Isididae", "Acanella", "Acanella");
addOption("Gorgonacea-Isididae", "Acanthoisis", "Acanthoisis");
addOption("Gorgonacea-Isididae", "Australisis", "Australisis");
addOption("Gorgonacea-Isididae", "Bathygorgia", "Bathygorgia");
addOption("Gorgonacea-Isididae", "Caribisis", "Caribisis");
addOption("Gorgonacea-Isididae", "Chathamisis", "Chathamisis");
addOption("Gorgonacea-Isididae", "Chelidonisis", "Chelidonisis");
addOption("Gorgonacea-Isididae", "Echinisis", "Echinisis");
addOption("Gorgonacea-Isididae", "Eknomisis", "Eknomisis");
addOption("Gorgonacea-Isididae", "Isidella", "Isidella");
addOption("Gorgonacea-Isididae", "Isis", "Isis");
addOption("Gorgonacea-Isididae", "Jasonisis", "Jasonisis");
addOption("Gorgonacea-Isididae", "Keratoisis", "Keratoisis");
addOption("Gorgonacea-Isididae", "Keratoisis cf.", "Keratoisis cf.");
addOption("Gorgonacea-Isididae", "Lepidisis", "Lepidisis");
addOption("Gorgonacea-Isididae", "Mopsea", "Mopsea");
addOption("Gorgonacea-Isididae", "Notisis", "Notisis");
addOption("Gorgonacea-Isididae", "Orstomisis", "Orstomisis");
addOption("Gorgonacea-Isididae", "Paracanthoisis", "Paracanthoisis");
addOption("Gorgonacea-Isididae", "Primnoisis", "Primnoisis");
addOption("Gorgonacea-Isididae", "Pteronisis", "Pteronisis");
addOption("Gorgonacea-Isididae", "Sclerisis", "Sclerisis");
addOption("Gorgonacea-Isididae", "Sphaerokodisis", "Sphaerokodisis");
addOption("Gorgonacea-Isididae", "Stenisis", "Stenisis");
addOption("Gorgonacea-Isididae", "Tenuisis", "Tenuisis");
addOption("Gorgonacea-Isididae", "NA", "NA");
addOption("Gorgonacea-Keroeididae", "Select Genus", "None");
addOption("Gorgonacea-Keroeididae", "Keroeides", "Keroeides");
addOption("Gorgonacea-Keroeididae", "Pseudothelogorgia", "Pseudothelogorgia");
addOption("Gorgonacea-Keroeididae", "Thelogorgia", "Thelogorgia");
addOption("Gorgonacea-Keroeididae", "NA", "NA");
addOption("Gorgonacea-Melithaeidae", "Select Genus", "None");
addOption("Gorgonacea-Melithaeidae", "Melithaea", "Melithaea");
addOption("Gorgonacea-Melithaeidae", "NA", "NA");
addOption("Gorgonacea-Paragorgiidae", "Select Genus", "None");
addOption("Gorgonacea-Paragorgiidae", "Paragorgia", "Paragorgia");
addOption("Gorgonacea-Paragorgiidae", "Sibogagorgia", "Sibogagorgia");
addOption("Gorgonacea-Paragorgiidae", "NA", "NA");
addOption("Gorgonacea-Paramuriceidae", "Select Genus", "None");
addOption("Gorgonacea-Paramuriceidae", "NA", "NA");
addOption("Gorgonacea-Parisididae", "Select Genus", "None");
addOption("Gorgonacea-Parisididae", "Parisis", "Parisis");
addOption("Gorgonacea-Plexauridae", "Select Genus", "None");
addOption("Gorgonacea-Plexauridae", "Acanthacis", "Acanthacis");
//addOption("Gorgonacea-Plexauridae", "Acanthomuricea", "Acanthomuricea");
addOption("Gorgonacea-Plexauridae", "Alaskagorgia", "Alaskagorgia");
addOption("Gorgonacea-Plexauridae", "Anthomuricea", "Anthomuricea");
addOption("Gorgonacea-Plexauridae", "Astrogorgia", "Astrogorgia");
addOption("Gorgonacea-Plexauridae", "Bayergorgia", "Bayergorgia");
addOption("Gorgonacea-Plexauridae", "Bebryce", "Bebryce");
//addOption("Gorgonacea-Plexauridae", "Caliacis", "Caliacis");
addOption("Gorgonacea-Plexauridae", "Chromoplexaura", "Chromoplexaura");
addOption("Gorgonacea-Plexauridae", "Cryogorgia", "Cryogorgia");
addOption("Gorgonacea-Plexauridae", "Echinogorgia", "Echinogorgia");
addOption("Gorgonacea-Plexauridae", "Echinomuricea", "Echinomuricea");
addOption("Gorgonacea-Plexauridae", "Elasmogorgia", "Elasmogorgia");
addOption("Gorgonacea-Plexauridae", "Euplexaura", "Euplexaura");
//addOption("Gorgonacea-Plexauridae", "Eunicea", "Eunicea");
addOption("Gorgonacea-Plexauridae", "Heterogorgia", "Heterogorgia");
addOption("Gorgonacea-Plexauridae", "Hypnogorgia", "Hypnogorgia");
addOption("Gorgonacea-Plexauridae", "Lytreia", "Lytreia");
addOption("Gorgonacea-Plexauridae", "Menella", "Menella");
addOption("Gorgonacea-Plexauridae", "Muricea", "Muricea");
addOption("Gorgonacea-Plexauridae", "Muriceides", "Muriceides");
addOption("Gorgonacea-Plexauridae", "Muriceopsis", "Muriceopsis");
addOption("Gorgonacea-Plexauridae", "Paracis", "Paracis");
addOption("Gorgonacea-Plexauridae", "Paramuricea", "Paramuricea");
//addOption("Gorgonacea-Plexauridae", "Paraplexaura", "Paraplexaura");
addOption("Gorgonacea-Plexauridae", "Placogorgia", "Placogorgia");
addOption("Gorgonacea-Plexauridae", "Plexaura", "Plexaura");
addOption("Gorgonacea-Plexauridae", "Plexaurella", "Plexaurella");
addOption("Gorgonacea-Plexauridae", "Plumarella", "Plumarella");
addOption("Gorgonacea-Plexauridae", "Possibly chromoplexaura", "Possibly chromoplexaura");
addOption("Gorgonacea-Plexauridae", "Psammogorgia", "Psammogorgia");
addOption("Gorgonacea-Plexauridae", "Pseudoplexaura", "Pseudoplexaura");
addOption("Gorgonacea-Plexauridae", "Pseudothesea", "Pseudothesea");
addOption("Gorgonacea-Plexauridae", "Pseudothesea sp", "Pseudothesea sp");
addOption("Gorgonacea-Plexauridae", "Scleracis", "Scleracis");
addOption("Gorgonacea-Plexauridae", "Spinimuricea", "Spinimuricea");
addOption("Gorgonacea-Plexauridae", "Swiftia", "Swiftia");
addOption("Gorgonacea-Plexauridae", "Thesea", "Thesea");
addOption("Gorgonacea-Plexauridae", "Trichogorgia", "Trichogorgia");
addOption("Gorgonacea-Plexauridae", "Villogorgia", "Villogorgia");
addOption("Gorgonacea-Plexauridae", "NA", "NA");
addOption("Gorgonacea-Primnoidae", "Select Genus", "None");
addOption("Gorgonacea-Primnoidae", "Abyssoprimnoa", "Abyssoprimnoa");
addOption("Gorgonacea-Primnoidae", "Acanthoprimnoa", "Acanthoprimnoa");
addOption("Gorgonacea-Primnoidae", "Aglaoprimnoa", "Aglaoprimnoa");
addOption("Gorgonacea-Primnoidae", "Ainigmaptilon", "Ainigmaptilon");
addOption("Gorgonacea-Primnoidae", "Armadillogorgia", "Armadillogorgia");
addOption("Gorgonacea-Primnoidae", "Arntzia", "Arntzia");
addOption("Gorgonacea-Primnoidae", "Arthrogorgia", "Arthrogorgia");
addOption("Gorgonacea-Primnoidae", "Australogorgia", "Australogorgia");
addOption("Gorgonacea-Primnoidae", "Callogorgia", "Callogorgia");
addOption("Gorgonacea-Primnoidae", "Callozostron", "Callozostron");
addOption("Gorgonacea-Primnoidae", "Calyptrophora", "Calyptrophora");
addOption("Gorgonacea-Primnoidae", "Candidella", "Candidella");
addOption("Gorgonacea-Primnoidae", "Convexella", "Convexella");
addOption("Gorgonacea-Primnoidae", "Dasystenella", "Dasystenella");
addOption("Gorgonacea-Primnoidae", "Digitogorgia", "Digitogorgia");
addOption("Gorgonacea-Primnoidae", "Fanellia", "Fanellia");
addOption("Gorgonacea-Primnoidae", "Fannyella", "Fannyella");
addOption("Gorgonacea-Primnoidae", "Helicoprimnoa", "Helicoprimnoa");
addOption("Gorgonacea-Primnoidae", "Heptaprimnoa", "Heptaprimnoa");
addOption("Gorgonacea-Primnoidae", "Metafannyella", "Metafannyella");
addOption("Gorgonacea-Primnoidae", "Metanarella", "Metanarella");
addOption("Gorgonacea-Primnoidae", "Microprimnoa", "Microprimnoa");
addOption("Gorgonacea-Primnoidae", "Mirostenella", "Mirostenella");
addOption("Gorgonacea-Primnoidae", "Narella", "Narella");
addOption("Gorgonacea-Primnoidae", "Narelloides", "Narelloides");
addOption("Gorgonacea-Primnoidae", "Onogorgia", "Onogorgia");
addOption("Gorgonacea-Primnoidae", "Ophidiogorgia", "Ophidiogorgia");
addOption("Gorgonacea-Primnoidae", "Paracalyptrophora", "Paracalyptrophora");
addOption("Gorgonacea-Primnoidae", "Paranarella", "Paranarella");
addOption("Gorgonacea-Primnoidae", "Parastenella", "Parastenella");
addOption("Gorgonacea-Primnoidae", "Perissogorgia", "Perissogorgia");
addOption("Gorgonacea-Primnoidae", "Plumarella", "Plumarella");
addOption("Gorgonacea-Primnoidae", "Plumarella (Dicholaphis)", "Plumarella (Dicholaphis)");
addOption("Gorgonacea-Primnoidae", "Primnoa", "Primnoa");
addOption("Gorgonacea-Primnoidae", "Primnoeides", "Primnoeides");
addOption("Gorgonacea-Primnoidae", "Primnoella", "Primnoella");
addOption("Gorgonacea-Primnoidae", "Pseudoplumarella", "Pseudoplumarella");
addOption("Gorgonacea-Primnoidae", "Pterostenella", "Pterostenella");
addOption("Gorgonacea-Primnoidae", "Pyrogorgia", "Pyrogorgia");
addOption("Gorgonacea-Primnoidae", "Tauroprimnoa", "Tauroprimnoa");
addOption("Gorgonacea-Primnoidae", "Thouarella", "Thouarella");
addOption("Gorgonacea-Primnoidae", "Tokoprymno", "Tokoprymno");
addOption("Gorgonacea-Primnoidae", "NA", "NA");
addOption("Gorgonacea-Spongiodermidae", "Select Genus", "None");
addOption("Gorgonacea-Spongiodermidae", "Callipodium", "Callipodium");
addOption("Gorgonacea-Spongiodermidae", "Diodogorgia", "Diodogorgia");
addOption("Gorgonacea-Spongiodermidae", "Titanideum", "Titanideum");
addOption("Gorgonacea-Spongiodermidae", "Tripalea", "Tripalea");
addOption("Gorgonacea-Subergorgiidae", "Select Genus", "None");
addOption("Gorgonacea-Subergorgiidae", "Rosgorgia", "Rosgorgia");

addOption("Helioporacea", "Select Family", "None", "None", 1);
addList("Helioporacea", "Lithotelestidae", "Lithotelestidae", "Helioporacea-Lithotelestidae");
addOption("Helioporacea-Lithotelestidae", "Select Genus", "None");
addOption("Helioporacea-Lithotelestidae", "Epiphaxum", "Epiphaxum");

addOption("Leptothecata", "Select Family", "None", "None", 1);
addList("Leptothecata", "Haleciidae", "Haleciidae", "Leptothecata-Haleciidae");
addOption("Leptothecata-Haleciidae", "Select Genus", "None");
addOption("Leptothecata-Haleciidae", "Hydrodendron", "Hydrodendron");

//addOption("Narcomedusae", "Select Family", "None", "None", 1);
//addList("Narcomedusae", "Aeginidae", "Aeginidae", "Narcomedusae-Aeginidae");
//addOption("Narcomedusae-Aeginidae", "Select Genus", "None");
//addOption("Narcomedusae-Aeginidae", "Aegina", "Aegina");

addOption("Pennatulacea", "Select Family", "None", "None", 1);
addList("Pennatulacea", "Anthoptilidae", "Anthoptilidae", "Pennatulacea-Anthoptilidae");
addList("Pennatulacea", "Anthothelidae", "Anthothelidae", "Pennatulacea-Anthothelidae");
addList("Pennatulacea", "Chunellidae", "Chunellidae", "Pennatulacea-Chunellidae");
addList("Pennatulacea", "Echinoptilidae", "Echinoptilidae", "Pennatulacea-Echinoptilidae");
addList("Pennatulacea", "Funiculinidae", "Funiculinidae", "Pennatulacea-Funiculinidae");
addList("Pennatulacea", "Halipteridae", "Halipteridae", "Pennatulacea-Halipteridae");
addList("Pennatulacea", "Kophobelemnidae", "Kophobelemnidae", "Pennatulacea-Kophobelemnidae");
addList("Pennatulacea", "Kophobelemnidae cf", "Kophobelemnidae cf", "Pennatulacea-Kophobelemnidae cf");
addList("Pennatulacea", "Pennatulidae", "Pennatulidae", "Pennatulacea-Pennatulidae");
addList("Pennatulacea", "Protoptilidae", "Protoptilidae", "Pennatulacea-Protoptilidae");
addList("Pennatulacea", "Renillidae", "Renillidae", "Pennatulacea-Renillidae");
addList("Pennatulacea", "Scleroptilidae", "Scleroptilidae", "Pennatulacea-Scleroptilidae");
addList("Pennatulacea", "Stachyptilidae", "Stachyptilidae", "Pennatulacea-Stachyptilidae");
addList("Pennatulacea", "Umbellulidae", "Umbellulidae", "Pennatulacea-Umbellulidae");
addList("Pennatulacea", "Veretillidae", "Veretillidae", "Pennatulacea-Veretillidae");
addList("Pennatulacea", "Virgulariidae", "Virgulariidae", "Pennatulacea-Virgulariidae");
addList("Pennatulacea", "NA", "NA", "Pennatulacea-NA");
addOption("Pennatulacea-Anthoptilidae", "Select Genus", "None");
addOption("Pennatulacea-Anthoptilidae", "Anthoptilum", "Anthoptilum");
addOption("Pennatulacea-Anthoptilidae", "Anthoptilum cf.", "Anthoptilum cf.");
addOption("Pennatulacea-Anthoptilidae", "NA", "NA");
addOption("Pennatulacea-Anthothelidae", "Select Genus", "None");
addOption("Pennatulacea-Anthothelidae", "Anthoptilum", "Anthoptilum");
addOption("Pennatulacea-Chunellidae", "Select Genus", "None");
addOption("Pennatulacea-Chunellidae", "Chunella", "Chunella");
addOption("Pennatulacea-Echinoptilidae", "Select Genus", "None");
addOption("Pennatulacea-Echinoptilidae", "Echinoptilum", "Echinoptilum");
addOption("Pennatulacea-Funiculinidae", "Select Genus", "None");
addOption("Pennatulacea-Funiculinidae", "Funiculina", "Funiculina");
addOption("Pennatulacea-Funiculinidae", "NA", "NA");
addOption("Pennatulacea-Halipteridae", "Select Genus", "None");
addOption("Pennatulacea-Halipteridae", "Halipteris", "Halipteris");
addOption("Pennatulacea-Halipteridae", "NA", "NA");
addOption("Pennatulacea-Kophobelemnidae", "Select Genus", "None");
addOption("Pennatulacea-Kophobelemnidae", "Kophobelemnon", "Kophobelemnon");
addOption("Pennatulacea-Kophobelemnidae", "Sclerobelemnon", "Sclerobelemnon");
addOption("Pennatulacea-Kophobelemnidae", "NA", "NA");
addOption("Pennatulacea-Kophobelemnidae cf", "Select Genus", "None");
addOption("Pennatulacea-Kophobelemnidae cf", "Malacobelemnon", "Malacobelemnon");
addOption("Pennatulacea-Kophobelemnidae cf", "NA", "NA");
addOption("Pennatulacea-Pennatulidae", "Select Genus", "None");
addOption("Pennatulacea-Pennatulidae", "Gyrophyllum", "Gyrophyllum");
addOption("Pennatulacea-Pennatulidae", "Pennatula", "Pennatula");
addOption("Pennatulacea-Pennatulidae", "Pteroeides", "Pteroeides");
addOption("Pennatulacea-Pennatulidae", "Ptilosarcus", "Ptilosarcus");
addOption("Pennatulacea-Pennatulidae", "NA", "NA");
addOption("Pennatulacea-Protoptilidae", "Select Genus", "None");
addOption("Pennatulacea-Protoptilidae", "Distichoptilum", "Distichoptilum");
addOption("Pennatulacea-Protoptilidae", "Protoptilum", "Protoptilum");
addOption("Pennatulacea-Protoptilidae", "NA", "NA");
addOption("Pennatulacea-Renillidae", "Select Genus", "None");
addOption("Pennatulacea-Renillidae", "Renilla", "Renilla");
addOption("Pennatulacea-Renillidae", "NA", "NA");
addOption("Pennatulacea-Scleroptilidae", "Select Genus", "None");
addOption("Pennatulacea-Scleroptilidae", "Calibelemnon", "Calibelemnon");
addOption("Pennatulacea-Scleroptilidae", "Scleroptilum", "Scleroptilum");
addOption("Pennatulacea-Scleroptilidae", "NA", "NA");
addOption("Pennatulacea-Stachyptilidae", "Select Genus", "None");
addOption("Pennatulacea-Stachyptilidae", "Stachyptilum", "Stachyptilum");
addOption("Pennatulacea-Umbellulidae", "Select Genus", "None");
addOption("Pennatulacea-Umbellulidae", "Umbellula", "Umbellula");
addOption("Pennatulacea-Umbellulidae", "NA", "NA");
addOption("Pennatulacea-Veretillidae", "Select Genus", "None");
//addOption("Pennatulacea-Veretillidae", "Amphibelemnon", "Amphibelemnon");
addOption("Pennatulacea-Veretillidae", "Cavernularia", "Cavernularia");
addOption("Pennatulacea-Veretillidae", "Cavernulina", "Cavernulina");
addOption("Pennatulacea-Veretillidae", "Veretillum", "Veretillum");
addOption("Pennatulacea-Virgulariidae", "Select Genus", "None");
addOption("Pennatulacea-Virgulariidae", "Acanthoptilum", "Acanthoptilum");
addOption("Pennatulacea-Virgulariidae", "Scytalium", "Scytalium");
addOption("Pennatulacea-Virgulariidae", "Stylatula", "Stylatula");
addOption("Pennatulacea-Virgulariidae", "Virgularia", "Virgularia");
addOption("Pennatulacea-Virgulariidae", "NA", "NA");

addOption("Scleractinia", "Select Family", "None", "None", 1);
//addList("Scleractinia", "Agariciidae", "Agariciidae", "Scleractinia-Agariciidae");
addList("Scleractinia", "Anthemiphylliidae", "Anthemiphylliidae", "Scleractinia-Anthemiphylliidae");
addList("Scleractinia", "Astrocoeniidae", "Astrocoeniidae", "Scleractinia-Astrocoeniidate");
addList("Scleractinia", "Caryophylliidae", "Caryophylliidae", "Scleractinia-Caryophylliidae");
addList("Scleractinia", "Deltocyathidae", "Deltocyathidae", "Scleractinia-Deltocyathidae");
addList("Scleractinia", "Dendrophylliidae", "Dendrophylliidae", "Scleractinia-Dendrophylliidae");
addList("Scleractinia", "Flabellidae", "Flabellidae", "Scleractinia-Flabellidae");
addList("Scleractinia", "Fungiacyathidae", "Fungiacyathidae", "Scleractinia-Fungiacyathidae");
addList("Scleractinia", "Fungiidae", "Fungiidae", "Scleractinia-Fungiidae");
addList("Scleractinia", "Gardineriidae", "Gardineriidae", "Scleractinia-Gardineriidae");
addList("Scleractinia", "Guyniidae", "Guyniidae", "Scleractinia-Guyniidae");
addList("Scleractinia", "Meandrinidae", "Meandrinidae", "Scleractinia-Meandrinidae");
//addList("Scleractinia", "Merulinidae", "Merulinidae", "Scleractinia-Merulinidae");
addList("Scleractinia", "Micrabaciidae", "Micrabaciidae", "Scleractinia-Micrabaciidae");
//addList("Scleractinia", "Montastraeidae", "Montastraeidae", "Scleractinia-Montastraeidae");
//addList("Scleractinia", "Mussidae", "Mussidae", "Scleractinia-Mussidae");
addList("Scleractinia", "Oculinidae", "Oculinidae", "Scleractinia-Oculinidae");
addList("Scleractinia", "Pocilloporidae", "Pocilloporidae", "Scleractinia-Pocilloporidae");
//addList("Scleractinia", "Poritidae", "Poritidae", "Scleractinia-Poritidae");
addList("Scleractinia", "Rhizangiidae", "Rhizangiidae", "Scleractinia-Rhizangiidae");
addList("Scleractinia", "Schizocyathidae", "Schizocyathidae", "Scleractinia-Schizocyathidae"); 
addList("Scleractinia", "Scleractinia incertae sedis", "Scleractinia incertae sedis", "Scleractinia-Scleractinia incertae sedis");
//addList("Scleractinia", "Siderastreidae", "Siderastreidae", "Scleractinia-Siderastreidae");
addList("Scleractinia", "Stenocyathidae", "Stenocyathidae", "Scleractinia-Stenocyathidae");
addList("Scleractinia", "Turbinoliidae", "Turbinoliidae", "Scleractinia-Turbinoliidae");
addList("Scleractinia", "NA", "NA", "Scleractinia-NA");
//addOption("Scleractinia-Agariciidae", "Select Genus", "None");
//addOption("Scleractinia-Agariciidae", "Agaricia", "Agaricia");
//addOption("Scleractinia-Agariciidae", "Helioseris", "Helioseris");
addOption("Scleractinia-Anthemiphylliidae", "Select Genus", "None");
addOption("Scleractinia-Anthemiphylliidae", "Anthemiphyllia", "Anthemiphyllia");
addOption("Scleractinia-Astrocoeniidate", "Select Genus", "None");
addOption("Scleractinia-Astrocoeniidate", "Madracis", "Madracis");
addOption("Scleractinia-Caryophylliidae", "Select Genus", "None");
addOption("Scleractinia-Caryophylliidae", "Anomocora", "Anomocora");
addOption("Scleractinia-Caryophylliidae", "Asterosmilia", "Asterosmilia");
addOption("Scleractinia-Caryophylliidae", "Aulocyathus", "Aulocyathus");
addOption("Scleractinia-Caryophylliidae", "Bathycyathus", "Bathycyathus");
addOption("Scleractinia-Caryophylliidae", "Bourneotrochus", "Bourneotrochus");
addOption("Scleractinia-Caryophylliidae", "Caryophyllia", "Caryophyllia");
//addOption("Scleractinia-Caryophylliidae", "Catalaphyllia", "Catalaphyllia");
addOption("Scleractinia-Caryophylliidae", "Ceratotrochus", "Ceratotrochus");
addOption("Scleractinia-Caryophylliidae", "Coenocyathus", "Coenocyathus");
addOption("Scleractinia-Caryophylliidae", "Coenosmilia", "Coenosmilia");
addOption("Scleractinia-Caryophylliidae", "Concentrotheca", "Concentrotheca");
addOption("Scleractinia-Caryophylliidae", "Confluphyllia", "Confluphyllia");
addOption("Scleractinia-Caryophylliidae", "Conotrochus", "Conotrochus");
addOption("Scleractinia-Caryophylliidae", "Crispatotrochus", "Crispatotrochus");
addOption("Scleractinia-Caryophylliidae", "Dactylotrochus", "Dactylotrochus");
addOption("Scleractinia-Caryophylliidae", "Dasmosmilia", "Dasmosmilia");
addOption("Scleractinia-Caryophylliidae", "Deltocyathus", "Deltocyathus");
addOption("Scleractinia-Caryophylliidae", "Desmophyllum", "Desmophyllum");
addOption("Scleractinia-Caryophylliidae", "Ericiocyathus", "Ericiocyathus");
//addOption("Scleractinia-Caryophylliidae", "Euphyllia", "Euphyllia");
addOption("Scleractinia-Caryophylliidae", "Goniocorella", "Goniocorella");
addOption("Scleractinia-Caryophylliidae", "Heterocyathus", "Heterocyathus");
//addOption("Scleractinia-Caryophylliidae", "Hoplangia", "Hoplangia");
addOption("Scleractinia-Caryophylliidae", "Labyrinthocyathus", "Labyrinthocyathus");
addOption("Scleractinia-Caryophylliidae", "Lochmaeotrochus", "Lochmaeotrochus");
addOption("Scleractinia-Caryophylliidae", "Lophelia", "Lophelia");
addOption("Scleractinia-Caryophylliidae", "Monohedotrochus", "Monohedotrochus");
addOption("Scleractinia-Caryophylliidae", "Oxysmilia", "Oxysmilia");
addOption("Scleractinia-Caryophylliidae", "Paraconotrochus", "Paraconotrochus");
addOption("Scleractinia-Caryophylliidae", "Paracyathus", "Paracyathus");
addOption("Scleractinia-Caryophylliidae", "Phacelocyathus", "Phacelocyathus");
addOption("Scleractinia-Caryophylliidae", "Phyllangia", "Phyllangia");
addOption("Scleractinia-Caryophylliidae", "Polycyathus", "Polycyathus");
addOption("Scleractinia-Caryophylliidae", "Pourtalosmilia", "Pourtalosmilia");
addOption("Scleractinia-Caryophylliidae", "Premocyathus", "Premocyathus");
addOption("Scleractinia-Caryophylliidae", "Rhizosmilia", "Rhizosmilia");
addOption("Scleractinia-Caryophylliidae", "Solenosmilia", "Solenosmilia");
addOption("Scleractinia-Caryophylliidae", "Stephanocyathus", "Stephanocyathus");
addOption("Scleractinia-Caryophylliidae", "Sympodangia", "Sympodangia");
addOption("Scleractinia-Caryophylliidae", "Tethocyathus", "Tethocyathus");
addOption("Scleractinia-Caryophylliidae", "Thalamophyllia", "Thalamophyllia");
addOption("Scleractinia-Caryophylliidae", "Trochocyathus", "Trochocyathus");
addOption("Scleractinia-Caryophylliidae", "Trochocyathus sp", "Trochocyathus sp");
//addOption("Scleractinia-Caryophylliidae", "Turbinolia", "Turbinolia");
addOption("Scleractinia-Caryophylliidae", "Vaughanella", "Vaughanella");
addOption("Scleractinia-Caryophylliidae", "NA", "NA");
addOption("Scleractinia-Deltocyathidae", "Select Genus", "None");
addOption("Scleractinia-Deltocyathidae", "Deltocyathus", "Deltocyathus");
addOption("Scleractinia-Dendrophylliidae", "Select Genus", "None");
addOption("Scleractinia-Dendrophylliidae", "Balanophyllia", "Balanophyllia");
addOption("Scleractinia-Dendrophylliidae", "Bathypsammia", "Bathypsammia");
addOption("Scleractinia-Dendrophylliidae", "Cladopsammia", "Cladopsammia");
addOption("Scleractinia-Dendrophylliidae", "Dendrophyllia", "Dendrophyllia");
addOption("Scleractinia-Dendrophylliidae", "Eguchipsammia", "Eguchipsammia");
addOption("Scleractinia-Dendrophylliidae", "Enallopsammia", "Enallopsammia");
addOption("Scleractinia-Dendrophylliidae", "Endopachys", "Endopachys");
addOption("Scleractinia-Dendrophylliidae", "Endopsammia", "Endopsammia");
addOption("Scleractinia-Dendrophylliidae", "Heteropsammia", "Heteropsammia");
addOption("Scleractinia-Dendrophylliidae", "Leptopsammia", "Leptopsammia");
addOption("Scleractinia-Dendrophylliidae", "Notophyllia", "Notophyllia");
addOption("Scleractinia-Dendrophylliidae", "Pourtalopsammia", "Pourtalopsammia");
addOption("Scleractinia-Dendrophylliidae", "Rhizopsammia", "Rhizopsammia");
addOption("Scleractinia-Dendrophylliidae", "Thecopsammia", "Thecopsammia");
addOption("Scleractinia-Dendrophylliidae", "Trochopsammia", "Trochopsammia");
addOption("Scleractinia-Dendrophylliidae", "Tubastraea", "Tubastraea");
addOption("Scleractinia-Dendrophylliidae", "Turbinaria", "Turbinaria");
addOption("Scleractinia-Dendrophylliidae", "NA", "NA");
addOption("Scleractinia-Flabellidae", "Select Genus", "None");
addOption("Scleractinia-Flabellidae", "Flabellum", "Flabellum");
addOption("Scleractinia-Flabellidae", "Javania", "Javania");
addOption("Scleractinia-Flabellidae", "Placotrochides", "Placotrochides");
addOption("Scleractinia-Flabellidae", "Placotrochus", "Placotrochus");
addOption("Scleractinia-Flabellidae", "Polymyces", "Polymyces");
addOption("Scleractinia-Flabellidae", "Rhizotrochus", "Rhizotrochus");
addOption("Scleractinia-Flabellidae", "Truncatoflabellum", "Truncatoflabellum");
addOption("Scleractinia-Flabellidae", "NA", "NA");
addOption("Scleractinia-Fungiacyathidae", "Select Genus", "None");
addOption("Scleractinia-Fungiacyathidae", "Fungiacyathus", "Fungiacyathus");
addOption("Scleractinia-Fungiidae", "Select Genus", "None");
addOption("Scleractinia-Fungiidae", "NA", "NA");
addOption("Scleractinia-Gardineriidae", "Select Genus", "None");
addOption("Scleractinia-Gardineriidae", "Gardineria", "Gardineria");
addOption("Scleractinia-Guyniidae", "Select Genus", "None");
addOption("Scleractinia-Guyniidae", "Guynia", "Guynia");
addOption("Scleractinia-Guyniidae", "Stenocyathus", "Stenocyathus");
addOption("Scleractinia-Guyniidae", "NA", "NA");
addOption("Scleractinia-Meandrinidae", "Select Genus", "None");
addOption("Scleractinia-Meandrinidae", "Dichocoenia", "Dichocoenia");
//addOption("Scleractinia-Meandrinidae", "Eusmilia", "Eusmilia");
//addOption("Scleractinia-Merulinidae", "Select Genus", "None");
//addOption("Scleractinia-Merulinidae", "Mycedium", "Mycedium");
//addOption("Scleractinia-Merulinidae", "Orbicella", "Orbicella");
addOption("Scleractinia-Micrabaciidae", "Select Genus", "None");
addOption("Scleractinia-Micrabaciidae", "Leptopenus", "Leptopenus");
addOption("Scleractinia-Micrabaciidae", "Letepsammia", "Letepsammia");
//addOption("Scleractinia-Montastraeidae", "Select Genus", "None");
//addOption("Scleractinia-Montastraeidae", "Montastraea", "Montastraea");
//addOption("Scleractinia-Mussidae", "Select Genus", "None");
//addOption("Scleractinia-Mussidae", "Colpopphyllia", "Colpopphyllia");
//addOption("Scleractinia-Mussidae", "Mussa", "Mussa");
//addOption("Scleractinia-Mussidae", "Mycetophyllia", "Mycetophyllia");
//addOption("Scleractinia-Mussidae", "Scolymia", "Scolymia");
addOption("Scleractinia-Oculinidae", "Select Genus", "None");
addOption("Scleractinia-Oculinidae", "Bathelia", "Bathelia");
addOption("Scleractinia-Oculinidae", "Cyathelia", "Cyathelia");
addOption("Scleractinia-Oculinidae", "Madrepora", "Madrepora");
addOption("Scleractinia-Oculinidae", "Oculina", "Oculina");
addOption("Scleractinia-Oculinidae", "NA", "NA");
addOption("Scleractinia-Pocilloporidae", "Select Genus", "None");
addOption("Scleractinia-Pocilloporidae", "Madracis", "Madracis");
//addOption("Scleractinia-Poritidae", "Select Genus", "None");
//addOption("Scleractinia-Poritidae", "Porites", "Porites");
addOption("Scleractinia-Rhizangiidae", "Select Genus", "None");
addOption("Scleractinia-Rhizangiidae", "Astrangia", "Astrangia");
addOption("Scleractinia-Rhizangiidae", "Culicia", "Culicia");
addOption("Scleractinia-Rhizangiidae", "Oulangia", "Oulangia");
addOption("Scleractinia-Schizocyathidae", "Select Genus", "None");
addOption("Scleractinia-Schizocyathidae", "Pourtalocyathus", "Pourtalocyathus");
addOption("Scleractinia-Schizocyathidae", "Schizocyathus", "Schizocyathus");
addOption("Scleractinia-Scleractinia incertae sedis", "Select Genus", "None");
addOption("Scleractinia-Scleractinia incertae sedis", "Cladocora", "Cladocora");
//addOption("Scleractinia-Siderastreidae", "Select Genus", "None");
//addOption("Scleractinia-Siderastreidae", "Siderastrea", "Siderastrea");
addOption("Scleractinia-Stenocyathidae", "Select Genus", "None");
addOption("Scleractinia-Stenocyathidae", "Stenocyathus", "Stenocyathus");
addOption("Scleractinia-Turbinoliidae", "Select Genus", "None");
addOption("Scleractinia-Turbinoliidae", "Alatotrochus", "Alatotrochus");
addOption("Scleractinia-Turbinoliidae", "Cryptotrochus", "Cryptotrochus");
addOption("Scleractinia-Turbinoliidae", "Cyathotrochus", "Cyathotrochus");
addOption("Scleractinia-Turbinoliidae", "Deltocyathoides", "Deltocyathoides");
addOption("Scleractinia-Turbinoliidae", "Endocyathopora", "Endocyathopora");
addOption("Scleractinia-Turbinoliidae", "Idiotrochus", "Idiotrochus");
addOption("Scleractinia-Turbinoliidae", "Notocyathus", "Notocyathus");
addOption("Scleractinia-Turbinoliidae", "Peponocyathus", "Peponocyathus");
addOption("Scleractinia-Turbinoliidae", "Sphenotrochus", "Sphenotrochus");
addOption("Scleractinia-Turbinoliidae", "Thrypticotrochus", "Thrypticotrochus");
addOption("Scleractinia-Turbinoliidae", "Trematotrochus", "Trematotrochus");
addOption("Scleractinia-Turbinoliidae", "Tropidocyathus", "Tropidocyathus");

//addOption("Siphonophorae", "Select Family", "None", "None", 1);
//addList("Siphonophorae", "Rhodaliidae", "Rhodaliidae", "Siphonophorae-Rhodaliidae");
//addOption("Siphonophorae-Rhodaliidae", "Select Genus", "None");
//addOption("Siphonophorae-Rhodaliidae", "Thermopalia", "Thermopalia");

addOption("Zoantharia", "Select Family", "None", "None", 1);
addList("Zoantharia", "Parazoanthidae", "Parazoanthidae", "Zoantharia-Parazoanthidae");
//addList("Zoantharia", "Zoanthidae", "Zoanthidae", "Zoantharia-Zoanthidae");
//addList("Zoantharia", "NA", "NA", "Zoantharia-NA");
addOption("Zoantharia-Parazoanthidae", "Select Genus", "None");
//addOption("Zoantharia-Parazoanthidae", "Bullagummizoanthus", "Bullagummizoanthus");
addOption("Zoantharia-Parazoanthidae", "Kulamanamana", "Kulamanamana");
//addOption("Zoantharia-Parazoanthidae", "Parazoanthus", "Parazoanthus");
addOption("Zoantharia-Parazoanthidae", "NA", "NA");
//addOption("Zoantharia-Zoanthidae", "Select Genus", "None");
//addOption("Zoantharia-Zoanthidae", "NA", "NA");

addOption("Porifera", "Select Order", "None", "None", 1);
addList("Porifera", "Agelasida", "Agelasida", "Agelasida");
addList("Porifera", "Amphidiscosida", "Amphidiscosida", "Amphidiscosida");
addList("Porifera", "Astrophorida", "Astrophorida", "Astrophorida");
addList("Porifera", "Aulocalycoida", "Aulocalycoida", "Aulocalycoida");
addList("Porifera", "Axinellida", "Axinellida", "Axinellida");
addList("Porifera", "Baerida", "Baerida", "Baerida");
addList("Porifera", "Biemnida", "Biemnida", "Biemnida");
addList("Porifera", "Bubarida", "Bubarida", "Bubarida");
addList("Porifera", "Chondrillida", "Chondrillida", "Chondrillida");
addList("Porifera", "Chondrosiida", "Chondrosiida", "Chondrosiida");
addList("Porifera", "Clathrinida", "Clathrinida", "Clathrinida");
addList("Porifera", "Clionaida", "Clionaida", "Clionaida");
addList("Porifera", "Dendroceratida", "Dendroceratida", "Dendroceratida");
addList("Porifera", "Desmacellida", "Desmacellida", "Desmacellida");
addList("Porifera", "Dictyoceratida", "Dictyoceratida", "Dictyoceratida");
addList("Porifera", "Hadromerida", "Hadromerida", "Hadromerida");
addList("Porifera", "Haplosclerida", "Haplosclerida", "Haplosclerida");
addList("Porifera", "Heteroscleromorpha incertae sedis", "Heteroscleromorpha incertae sedis", "Heteroscleromorpha incertae sedis");
addList("Porifera", "Hexactinosida", "Hexactinosida", "Hexactinosida");
addList("Porifera", "Hexasterophora incertae sedis", "Hexasterophora incertae sedis", "Hexasterophora incertae sedis");
addList("Porifera", "Homosclerophorida", "Homosclerophorida", "Homosclerophorida");
addList("Porifera", "Leucosolenida", "Leucosolenida", "Leucosolenida");
addList("Porifera", "Lithistida", "Lithistida", "Lithistida");
addList("Porifera", "Lychniscosida", "Lychniscosida", "Lychniscosida");
addList("Porifera", "Lyssacinosida", "Lyssacinosida", "Lyssacinosida");
addList("Porifera", "Merliida", "Merliida", "Merliida");
addList("Porifera", "Poecilosclerida", "Poecilosclerida", "Poecilosclerida");
addList("Porifera", "Polymastiida", "Polymastiida", "Polymastiida");
addList("Porifera", "Sceptrulophora", "Sceptrulophora", "Sceptrulophora");
addList("Porifera", "Scopalinida", "Scopalinida", "Scopalinida");
addList("Porifera", "Suberitida", "Suberitida", "Suberitida");
addList("Porifera", "Tethyida", "Tethyida", "Tethyida");
addList("Porifera", "Tetractinellida", "Tetractinellida", "Tetractinellida");
addList("Porifera", "Verongiida", "Verongiida", "Verongiida");
addList("Porifera", "NA", "NA", "Porifera-NA");

addOption("Porifera-NA", "Select Family", "None", "None", 1);

addOption("Agelasida", "Select Family", "None", "None", 1);
addList("Agelasida", "Agelasidae", "Agelasidae", "Agelasida-Agelasidae");
addOption("Agelasida-Agelasidae", "Select Genus", "None");
addOption("Agelasida-Agelasidae", "Agelas", "Agelas");

addOption("Amphidiscosida", "Select Family", "None", "None", 1);
addList("Amphidiscosida", "Hyalonematidae", "Hyalonematidae", "Amphidiscosida-Hyalonematidae");
addList("Amphidiscosida", "Pheronematidae", "Pheronematidae", "Amphidiscosida-Pheronematidae");
addList("Amphidiscosida", "NA", "NA", "Amphidiscosida-NA");
addOption("Amphidiscosida-Hyalonematidae", "Select Genus", "None");
addOption("Amphidiscosida-Hyalonematidae", "Hyalonema", "Hyalonema");
addOption("Amphidiscosida-Hyalonematidae", "NA", "NA");
addOption("Amphidiscosida-Pheronematidae", "Select Genus", "None");
addOption("Amphidiscosida-Pheronematidae", "Pheronema", "Pheronema");
addOption("Amphidiscosida-Pheronematidae", "Poliopogon", "Poliopogon");
addOption("Amphidiscosida-Pheronematidae", "Semperella", "Semperella");
addOption("Amphidiscosida-Pheronematidae", "Sericolophus", "Sericolophus");
addOption("Amphidiscosida-Pheronematidae", "NA", "NA");

addOption("Astrophorida", "Select Family", "None", "None", 1);
addList("Astrophorida", "Geodiidae", "Geodiidae", "Astrophorida-Geodiidae");
addOption("Astrophorida-Geodiidae", "Select Genus", "None");
addOption("Astrophorida-Geodiidae", "Erylus", "Erylus");

addOption("Aulocalycoida", "Select Family", "None", "None", 1);
addList("Aulocalycoida", "Aulocalycidae", "Aulocalycidae", "Aulocalycoida-Aulocalycidae");
addList("Aulocalycoida", "Uncinateridae", "Uncinateridae", "Aulocalycoida-Uncinateridae");
addOption("Aulocalycoida-Aulocalycidae", "Select Genus", "None");
addOption("Aulocalycoida-Aulocalycidae", "Leioplegma", "Leioplegma");
addOption("Aulocalycoida-Aulocalycidae", "Rhabdodictyum", "Rhabdodictyum");
addOption("Aulocalycoida-Uncinateridae", "Select Genus", "None");
addOption("Aulocalycoida-Uncinateridae", "Tretopleura", "Tretopleura");

addOption("Axinellida", "Select Family", "None", "None", 1);
addList("Axinellida", "Axinellidae", "Axinellidae", "Axinellida-Axinellidae");
addList("Axinellida", "Heteroxyidae", "Heteroxyidae", "Axinellida-Heteroxyidae");
addList("Axinellida", "Raspailiidae", "Raspailiidae", "Axinellida-Raspailiidae");
addList("Axinellida", "Stelligeridae", "Stelligeridae", "Axinellida-Stelligeridae");
addOption("Axinellida-Axinellidae", "Select Genus", "None");
addOption("Axinellida-Axinellidae", "Auletta", "Auletta");
addOption("Axinellida-Axinellidae", "Axinella", "Axinella");
addOption("Axinellida-Axinellidae", "Dragmacidon", "Dragmacidon");
addOption("Axinellida-Axinellidae", "Dragmaxia", "Dragmaxia");
addOption("Axinellida-Axinellidae", "Endectyon", "Endectyon");
addOption("Axinellida-Axinellidae", "Phakellia", "Phakellia");
addOption("Axinellida-Axinellidae", "Pseudaxinella", "Pseudaxinella");
addOption("Axinellida-Heteroxyidae", "Select Genus", "None");
//addOption("Axinellida-Heteroxyidae", "Didiscus", "Didiscus");
addOption("Axinellida-Heteroxyidae", "Myrmekioderma", "Myrmekioderma");
addOption("Axinellida-Raspailiidae", "Select Genus", "None");
addOption("Axinellida-Raspailiidae", "Ceratopsion", "Ceratopsion");
addOption("Axinellida-Raspailiidae", "Endectyon", "Endectyon");
addOption("Axinellida-Raspailiidae", "Eurypon", "Eurypon");
addOption("Axinellida-Raspailiidae", "Raspaciona", "Raspaciona");
addOption("Axinellida-Raspailiidae", "Raspailia", "Raspailia");
addOption("Axinellida-Raspailiidae", "Thrinacophora", "Thrinacophora");
addOption("Axinellida-Raspailiidae", "Trikentrion", "Trikentrion");
addOption("Axinellida-Raspailiidae", "NA", "NA")
addOption("Axinellida-Stelligeridae", "Select Genus", "None");
addOption("Axinellida-Stelligeridae", "Halicnemia", "Halicnemia");
addOption("Axinellida-Stelligeridae", "Higginsia", "Higginsia");

addOption("Baerida", "Select Family", "None", "None", 1);
addList("Baerida", "Baeriidae", "Baeriidae", "Baerida-Baeriidae");
addOption("Baerida-Baeriidae", "Select Genus", "None");
addOption("Baerida-Baeriidae", "Leuconia", "Leuconia");

addOption("Biemnida", "Select Family", "None", "None", 1);
addList("Biemnida", "Biemnidae", "Biemnidae", "Biemnida-Biemnidae");
addList("Biemnida", "Rhabderemiidae", "Rhabderemiidae", "Biemnida-Rhabderemiidae");
addOption("Biemnida-Biemnidae", "Select Genus", "None");
addOption("Biemnida-Biemnidae", "Biemna", "Biemna");
addOption("Biemnida-Biemnidae", "Neofibularia", "Neofibularia");
addOption("Biemnida-Rhabderemiidae", "Select Genus", "None");
addOption("Biemnida-Rhabderemiidae", "Rhabderemia", "Rhabderemia");

addOption("Bubarida", "Select Family", "None", "None", 1);
addList("Bubarida", "Bubaridae", "Bubaridae", "Bubarida-Bubaridae");
addList("Bubarida", "Dictyonellidae", "Dictyonellidae", "Bubarida-Dictyonellidae");
addOption("Bubarida-Bubaridae", "Select Genus", "None");
addOption("Bubarida-Bubaridae", "Bubaris", "Bubaris");
addOption("Bubarida-Bubaridae", "Cerbaris", "Cerbaris");
addOption("Bubarida-Dictyonellidae", "Select Genus", "None");
addOption("Bubarida-Dictyonellidae", "Acanthella", "Acanthella");
addOption("Bubarida-Dictyonellidae", "Lipastrotethya", "Lipastrotethya");
addOption("Bubarida-Dictyonellidae", "Phakettia", "Phakettia");
addOption("Bubarida-Dictyonellidae", "NA", "NA");

addOption("Chondrillida", "Select Family", "None", "None", 1);
addList("Chondrillida", "Chondrillidae", "Chondrillidae", "Chondrillida-Chondrillidae");
addList("Chondrillida", "Halisarcidae", "Halisarcidae", "Chondrillida-Halisarcidae");
addOption("Chondrillida-Chondrillidae", "Select Genus", "None");
addOption("Chondrillida-Chondrillidae", "Chondrilla", "Chondrilla");
addOption("Chondrillida-Halisarcidae", "Select Genus", "None");
addOption("Chondrillida-Halisarcidae", "Halisarca", "Halisarca");

addOption("Chondrosiida", "Select Family", "None", "None", 1);
addList("Chondrosiida", "Chondrosiidae", "Chondrosiidae", "Chondrosiida-Chondrosiidae");
addOption("Chondrosiida-Chondrosiidae", "Select Genus", "None");
addOption("Chondrosiida-Chondrosiidae", "Chondrosia", "Chondrosia");

addOption("Clathrinida", "Select Family", "None", "None", 1);
addList("Clathrinida", "Clathrinidae", "Clathrinidae", "Clathrinida-Clathrinidae");
addList("Clathrinida", "Leucettidae", "Leucettidae", "Clathrinida-Leucettidae");
addOption("Clathrinida-Clathrinidae", "Select Genus", "None");
addOption("Clathrinida-Clathrinidae", "Arthuria", "Arthuria");
addOption("Clathrinida-Clathrinidae", "Clathrina", "Clathrina");
addOption("Clathrinida-Clathrinidae", "Guancha", "Guancha");
addOption("Clathrinida-Clathrinidae", "NA", "NA");
addOption("Clathrinida-Leucettidae", "Select Genus", "None");
addOption("Clathrinida-Leucettidae", "Leucetta", "Leucetta");

addOption("Clionaida", "Select Family", "None", "None", 1);
addList("Clionaida", "Clionaidae", "Clionaidae", "Clionaida-Clionaidae");
addList("Clionaida", "Placospongiidae", "Placospongiidae", "Clionaida-Placospongiidae");
addList("Clionaida", "Spirastrellidae", "Spirastrellidae", "Clionaida-Spirastrellidae");
addOption("Clionaida-Clionaidae", "Select Genus", "None");
addOption("Clionaida-Clionaidae", "Cliona", "Cliona");
addOption("Clionaida-Clionaidae", "Pione", "Pione");
addOption("Clionaida-Clionaidae", "Scolopes", "Scolopes");
addOption("Clionaida-Clionaidae", "Spheciospongia", "Spheciospongia");
addOption("Clionaida-Placospongiidae", "Select Genus", "None");
addOption("Clionaida-Placospongiidae", "Placospongia", "Placospongia");
addOption("Clionaida-Spirastrellidae", "Select Genus", "None");
addOption("Clionaida-Spirastrellidae", "Diplastrella", "Diplastrella");
addOption("Clionaida-Spirastrellidae", "Spirastrella", "Spirastrella");
addOption("Clionaida-Spirastrellidae", "NA", "NA");

addOption("Dendroceratida", "Select Family", "None", "None", 1);
addList("Dendroceratida", "Darwinellidae", "Darwinellidae", "Dendroceratida-Darwinellidae");
addList("Dendroceratida", "Dictyodendrillidae", "Dictyodendrillidae", "Dendroceratida-Dictyodendrillidae");
//addList("Dendroceratida", "Dysideidae", "Dysideidae", "Dendroceratida-Dysideidae");
addOption("Dendroceratida-Darwinellidae", "Select Genus", "None");
addOption("Dendroceratida-Darwinellidae", "Aplysilla", "Aplysilla");
addOption("Dendroceratida-Darwinellidae", "Chelonaplysilla", "Chelonaplysilla");
addOption("Dendroceratida-Dictyodendrillidae", "Select Genus", "None");
addOption("Dendroceratida-Dictyodendrillidae", "Igernella", "Igernella");
//addOption("Dendroceratida-Dysideidae", "Select Genus", "None");
//addOption("Dendroceratida-Dysideidae", "Pleraplysilla", "Pleraplysilla");

addOption("Desmacellida", "Select Family", "None", "None", 1);
addList("Desmacellida", "Desmacellidae", "Desmacellidae", "Desmacellida-Desmacellidae");
addList("Desmacellida", "Desmacididae", "Desmacididae", "Desmacellida-Desmacididae");
addOption("Desmacellida-Desmacellidae", "Select Genus", "None");
addOption("Desmacellida-Desmacellidae", "Desmacella", "Desmacella");
addOption("Desmacellida-Desmacellidae", "NA", "NA");
addOption("Desmacellida-Desmacididae", "Select Genus", "None");
addOption("Desmacellida-Desmacididae", "NA", "NA");

addOption("Dictyoceratida", "Select Family", "None", "None", 1);
addList("Dictyoceratida", "Dysideidae", "Dysideidae", "Dictyoceratida-Dysideidae");
addList("Dictyoceratida", "Irciniidae", "Irciniidae", "Dictyoceratida-Irciniidae");
addList("Dictyoceratida", "Spongiidae", "Spongiidae", "Dictyoceratida-Spongiidae");
addList("Dictyoceratida", "Thorectidae", "Thorectidae", "Dictyoceratida-Thorectidae");
addList("Dictyoceratida", "NA", "NA", "Dictyoceratida-NA");
addOption("Dictyoceratida-Dysideidae", "Select Genus", "None");
addOption("Dictyoceratida-Dysideidae", "Dysidea", "Dysidea");
addOption("Dictyoceratida-Dysideidae", "Euryspongia", "Euryspongia");
addOption("Dictyoceratida-Dysideidae", "NA", "NA");
addOption("Dictyoceratida-Irciniidae", "Select Genus", "None");
addOption("Dictyoceratida-Irciniidae", "Ircinia", "Ircinia");
addOption("Dictyoceratida-Spongiidae", "Select Genus", "None");
addOption("Dictyoceratida-Spongiidae", "Hippospongia", "Hippospongia");
addOption("Dictyoceratida-Spongiidae", "Hyattella", "Hyattella");
addOption("Dictyoceratida-Spongiidae", "Spongia", "Spongia");
addOption("Dictyoceratida-Thorectidae", "Select Genus", "None");
addOption("Dictyoceratida-Thorectidae", "Cacospongia", "Cacospongia");
addOption("Dictyoceratida-Thorectidae", "Hyrtios", "Hyrtios");
addOption("Dictyoceratida-Thorectidae", "Smenospongia", "Smenospongia");
addOption("Dictyoceratida-Thorectidae", "NA", "NA");

addOption("Hadromerida", "Select Family", "None", "None", 1);
addList("Hadromerida", "Polymastiidae", "Polymastiidae", "Hadromerida-Polymastiidae");
addOption("Hadromerida-Polymastiidae", "Select Genus", "None");
addOption("Hadromerida-Polymastiidae", "NA", "NA");

addOption("Haplosclerida", "Select Family", "None", "None", 1);
addList("Haplosclerida", "Callyspongiidae", "Callyspongiidae", "Haplosclerida-Callyspongiidae");
addList("Haplosclerida", "Chalinidae", "Chalinidae", "Haplosclerida-Chalinidae");
addList("Haplosclerida", "Niphatidae", "Niphatidae", "Haplosclerida-Niphatidae");
addList("Haplosclerida", "Petrosiidae", "Petrosiidae", "Haplosclerida-Petrosiidae");
addList("Haplosclerida", "Phloeodictyidae", "Phloeodictyidae", "Haplosclerida-Phloeodictyidae");
addList("Haplosclerida", "NA", "NA", "Haplosclerida-NA");
addOption("Haplosclerida-Callyspongiidae", "Select Genus", "None");
addOption("Haplosclerida-Callyspongiidae", "Callyspongia", "Callyspongia");
addOption("Haplosclerida-Callyspongiidae", "Siphonochalina", "Siphonochalina");
addOption("Haplosclerida-Chalinidae", "Select Genus", "None");
addOption("Haplosclerida-Chalinidae", "Chalinula", "Chalinula");
addOption("Haplosclerida-Chalinidae", "Haliclona", "Haliclona");
addOption("Haplosclerida-Chalinidae", "NA", "NA");
addOption("Haplosclerida-Niphatidae", "Select Genus", "None");
addOption("Haplosclerida-Niphatidae", "Amphimedon", "Amphimedon");
addOption("Haplosclerida-Niphatidae", "Cribrochalina", "Cribrochalina");
addOption("Haplosclerida-Niphatidae", "Gelliodes", "Gelliodes");
addOption("Haplosclerida-Niphatidae", "Hemigellius", "Hemigellius");
addOption("Haplosclerida-Niphatidae", "Niphates", "Niphates");
addOption("Haplosclerida-Niphatidae", "NA", "NA");
addOption("Haplosclerida-Petrosiidae", "Select Genus", "None");
addOption("Haplosclerida-Petrosiidae", "Neopetrosia", "Neopetrosia");
addOption("Haplosclerida-Petrosiidae", "Petrosia", "Petrosia");
addOption("Haplosclerida-Petrosiidae", "Xestospongia", "Xestospongia");
addOption("Haplosclerida-Petrosiidae", "NA", "NA");
addOption("Haplosclerida-Phloeodictyidae", "Select Genus", "None");
addOption("Haplosclerida-Phloeodictyidae", "Calyx", "Calyx");
addOption("Haplosclerida-Phloeodictyidae", "Oceanapia", "Oceanapia");
addOption("Haplosclerida-Phloeodictyidae", "Siphonodictyon", "Siphonodictyon");

addOption("Heteroscleromorpha incertae sedis", "Select Family", "None", "None", 1);
addList("Heteroscleromorpha incertae sedis", "Lithistida incertae sedis", "Lithistida incertae sedis", "Heteroscleromorpha incertae sedis-Lithistida incertae sedis");
addOption("Heteroscleromorpha incertae sedis-Lithistida incertae sedis", "Select Genus", "None");
addOption("Heteroscleromorpha incertae sedis-Lithistida incertae sedis", "Poritella", "Poritella");

addOption("Hexactinosida", "Select Family", "None", "None", 1);
addList("Hexactinosida", "Aphrocallistidae", "Aphrocallistidae", "Hexactinosida-Aphrocallistidae");
addList("Hexactinosida", "Auloplacidae", "Auloplacidae", "Hexactinosida-Auloplacidae");
addList("Hexactinosida", "Dactylocalycidae", "Dactylocalycidae", "Hexactinosida-Dactylocalycidae");
addList("Hexactinosida", "Euretidae", "Euretidae", "Hexactinosida-Euretidae");
addList("Hexactinosida", "Farreidae", "Farreidae", "Hexactinosida-Farreidae");
addList("Hexactinosida", "Tretodictyidae", "Tretodictyidae", "Hexactinosida-Tretodictyidae");
addList("Hexactinosida", "NA", "NA", "Hexactinosida-NA");
addOption("Hexactinosida-Aphrocallistidae", "Select Genus", "None");
addOption("Hexactinosida-Aphrocallistidae", "Aphrocallistes", "Aphrocallistes");
addOption("Hexactinosida-Aphrocallistidae", "Heterochone", "Heterochone");
addOption("Hexactinosida-Auloplacidae", "Select Genus", "None");
addOption("Hexactinosida-Auloplacidae", "Auloplax", "Auloplax");
addOption("Hexactinosida-Dactylocalycidae", "Select Genus", "None");
addOption("Hexactinosida-Dactylocalycidae", "Dactylocalyx", "Dactylocalyx");
addOption("Hexactinosida-Dactylocalycidae", "Iphiteon", "Iphiteon");
addOption("Hexactinosida-Euretidae", "Select Genus", "None");
addOption("Hexactinosida-Euretidae", "Bathyxiphus", "Bathyxiphus");
addOption("Hexactinosida-Euretidae", "Chonelasma", "Chonelasma");
addOption("Hexactinosida-Euretidae", "Conorete", "Conorete");
addOption("Hexactinosida-Euretidae", "Endorete", "Endorete");
addOption("Hexactinosida-Euretidae", "Eurete", "Eurete");
addOption("Hexactinosida-Euretidae", "Heterorete", "Heterorete");
addOption("Hexactinosida-Euretidae", "Lefroyella", "Lefroyella");
addOption("Hexactinosida-Euretidae", "Myliusia", "Myliusia");
addOption("Hexactinosida-Euretidae", "Pararete", "Pararete");
addOption("Hexactinosida-Euretidae", "Periphragella", "Periphragella");
addOption("Hexactinosida-Euretidae", "Pinulasma", "Pinulasma");
addOption("Hexactinosida-Euretidae", "NA", "NA");
addOption("Hexactinosida-Farreidae", "Select Genus", "None");
addOption("Hexactinosida-Farreidae", "Asceptrulum", "Asceptrulum");
addOption("Hexactinosida-Farreidae", "Aspidoscopulia", "Aspidoscopulia");
addOption("Hexactinosida-Farreidae", "Claviscopulia", "Claviscopulia");
addOption("Hexactinosida-Farreidae", "Farrea", "Farrea");
addOption("Hexactinosida-Farreidae", "NA", "NA");
addOption("Hexactinosida-Tretodictyidae", "Select Genus", "None");
addOption("Hexactinosida-Tretodictyidae", "Cyrtaulon", "Cyrtaulon");
addOption("Hexactinosida-Tretodictyidae", "Hexactinella", "Hexactinella");
addOption("Hexactinosida-Tretodictyidae", "Psilocalyx", "Psilocalyx");
addOption("Hexactinosida-Tretodictyidae", "Sclerothamnopsis", "Sclerothamnopsis");
addOption("Hexactinosida-Tretodictyidae", "Tretodictyum", "Tretodictyum");
addOption("Hexactinosida-Tretodictyidae", "NA", "NA");

addOption("Hexasterophora incertae sedis", "Select Family", "None", "None", 1);
addList("Hexasterophora incertae sedis", "Dactylocalycidae", "Dactylocalycidae", "Hexasterophora incertae sedis-Dactylocalycidae");
addList("Hexasterophora incertae sedis", "NA", "NA", "Hexasterophora incertae sedis-NA");
addOption("Hexasterophora incertae sedis-Dactylocalycidae", "Select Genus", "None");
addOption("Hexasterophora incertae sedis-Dactylocalycidae", "Dactylocalyx", "Dactylocalyx");
addOption("Hexasterophora incertae sedis-Dactylocalycidae", "Iphiteon", "Iphiteon");

addOption("Homosclerophorida", "Select Family", "None", "None", 1);
addList("Homosclerophorida", "Oscarellidae", "Oscarellidae", "Homosclerophorida-Oscarellidae");
addList("Homosclerophorida", "Plakinidae", "Plakinidae", "Homosclerophorida-Plakinidae");
addOption("Homosclerophorida-Oscarellidae", "Select Genus", "None");
addOption("Homosclerophorida-Oscarellidae", "Oscarella", "Oscarella");
addOption("Homosclerophorida-Plakinidae", "Select Genus", "None");
addOption("Homosclerophorida-Plakinidae", "Corticium", "Corticium");
addOption("Homosclerophorida-Plakinidae", "Plakina", "Plakina");
addOption("Homosclerophorida-Plakinidae", "Plakortis", "Plakortis");
addOption("Homosclerophorida-Plakinidae", "NA", "NA");

addOption("Leucosolenida", "Select Family", "None", "None", 1);
addList("Leucosolenida", "Amphoriscidae", "Amphoriscidae", "Leucosolenida-Amphoriscidae");
addList("Leucosolenida", "Grantiidae", "Grantiidae", "Leucosolenida-Grantiidae");
addList("Leucosolenida", "Heteropiidae", "Heteropiidae", "Leucosolenida-Heteropiidae");
addList("Leucosolenida", "Leucosoleniidae", "Leucosoleniidae", "Leucosolenida-Leucosoleniidae");
addList("Leucosolenida", "Sycettidae", "Sycettidae", "Leucosolenida-Sycettidae");
addList("Leucosolenida", "NA", "NA", "Leucosolenida-NA");
addOption("Leucosolenida-Amphoriscidae", "Select Genus", "None");
addOption("Leucosolenida-Amphoriscidae", "Leucilla", "Leucilla"); 
addOption("Leucosolenida-Grantiidae", "Select Genus", "None");
addOption("Leucosolenida-Grantiidae", "Aphroceras", "Aphroceras");
addOption("Leucosolenida-Grantiidae", "Leucandra", "Leucandra");
addOption("Leucosolenida-Grantiidae", "Sycandra", "Sycandra");
addOption("Leucosolenida-Heteropiidae", "Select Genus", "None");
addOption("Leucosolenida-Heteropiidae", "Vosmaeropsis", "Vosmaeropsis");
addOption("Leucosolenida-Leucosoleniidae", "Select Genus", "None");
addOption("Leucosolenida-Leucosoleniidae", "Leucosolenia", "Leucosolenia");
addOption("Leucosolenida-Sycettidae", "Select Genus", "None");
addOption("Leucosolenida-Sycettidae", "Sycon", "Sycon");

addOption("Lithistida", "Select Family", "None", "None", 1);
addList("Lithistida", "Vetulinidae", "Vetulinidae", "Lithistida-Vetulinidae");
addList("Lithistida", "NA", "NA", "Lithistida-NA");
addOption("Lithistida-Vetulinidae", "Select Genus", "None");
addOption("Lithistida-Vetulinidae", "Vetulina", "Vetulina");

addOption("Lychniscosida", "Select Family", "None", "None", 1);
addList("Lychniscosida", "Aulocystidae", "Aulocystidae", "Lychniscosida-Aulocystidae");
addList("Lychniscosida", "Diapleuridae", "Diapleuridae", "Lychniscosida-Diapleuridae");
addOption("Lychniscosida-Aulocystidae", "Select Genus", "None");
addOption("Lychniscosida-Aulocystidae", "Lychnocystis", "Lychnocystis");
addOption("Lychniscosida-Aulocystidae", "Neoaulocystis", "Neoaulocystis");
addOption("Lychniscosida-Diapleuridae", "Select Genus", "None");
addOption("Lychniscosida-Diapleuridae", "Scleroplegma", "Scleroplegma");

addOption("Lyssacinosida", "Select Family", "None", "None", 1);
addList("Lyssacinosida", "Euplectellidae", "Euplectellidae", "Lyssacinosida-Euplectellidae");
addList("Lyssacinosida", "Leucopsacidae", "Leucopsacidae", "Lyssacinosida-Leucopsacidae");
addList("Lyssacinosida", "Rossellidae", "Rossellidae", "Lyssacinosida-Rossellidae");
addList("Lyssacinosida", "NA", "NA", "Lyssacinosida-NA");
addOption("Lyssacinosida-Euplectellidae", "Select Genus", "None");
addOption("Lyssacinosida-Euplectellidae", "Amphidiscella", "Amphidiscella");
addOption("Lyssacinosida-Euplectellidae", "Atlantisella", "Atlantisella");
addOption("Lyssacinosida-Euplectellidae", "Bolosoma", "Bolosoma");
addOption("Lyssacinosida-Euplectellidae", "Corbitella", "Corbitella");
addOption("Lyssacinosida-Euplectellidae", "Dictyaulus", "Dictyaulus");
addOption("Lyssacinosida-Euplectellidae", "Docosaccus", "Docosaccus");
addOption("Lyssacinosida-Euplectellidae", "Euplectella", "Euplectella");
addOption("Lyssacinosida-Euplectellidae", "Hertwigia", "Hertwigia");
addOption("Lyssacinosida-Euplectellidae", "Holascus", "Holascus");
addOption("Lyssacinosida-Euplectellidae", "Hyalostylus", "Hyalostylus");
addOption("Lyssacinosida-Euplectellidae", "Malacosaccus", "Malacosaccus");
addOption("Lyssacinosida-Euplectellidae", "Placopegma", "Placopegma");
addOption("Lyssacinosida-Euplectellidae", "Regadrella", "Regadrella");
addOption("Lyssacinosida-Euplectellidae", "Rhabdopectella", "Rhabdopectella");
addOption("Lyssacinosida-Euplectellidae", "Saccocalyx", "Saccocalyx");
addOption("Lyssacinosida-Euplectellidae", "Walteria", "Walteria");
addOption("Lyssacinosida-Euplectellidae", "NA", "NA");
addOption("Lyssacinosida-Leucopsacidae", "Select Genus", "None");
addOption("Lyssacinosida-Leucopsacidae", "NA", "NA");
addOption("Lyssacinosida-Rossellidae", "Select Genus", "None");
addOption("Lyssacinosida-Rossellidae", "Acanthascus", "Acanthascus");
addOption("Lyssacinosida-Rossellidae", "Aphorme", "Aphorme");
addOption("Lyssacinosida-Rossellidae", "Asconema", "Asconema");
addOption("Lyssacinosida-Rossellidae", "Aulosaccus", "Aulosaccus");
addOption("Lyssacinosida-Rossellidae", "Bathydorus", "Bathydorus");
addOption("Lyssacinosida-Rossellidae", "Calycosoma", "Calycosoma");
addOption("Lyssacinosida-Rossellidae", "Caulophacus", "Caulophacus");
addOption("Lyssacinosida-Rossellidae", "Hyalascus", "Hyalascus");
addOption("Lyssacinosida-Rossellidae", "Lophocalyx", "Lophocalyx");
addOption("Lyssacinosida-Rossellidae", "Nodastrella", "Nodastrella");
addOption("Lyssacinosida-Rossellidae", "Rhabdocalyptus", "Rhabdocalyptus");
addOption("Lyssacinosida-Rossellidae", "Rossella", "Rossella");
addOption("Lyssacinosida-Rossellidae", "Schaudinnia", "Schaudinnia");
addOption("Lyssacinosida-Rossellidae", "Scyphidium", "Scyphidium");
addOption("Lyssacinosida-Rossellidae", "Staurocalyptus", "Staurocalyptus");
addOption("Lyssacinosida-Rossellidae", "Sympagella", "Sympagella");
addOption("Lyssacinosida-Rossellidae", "Trichasterina", "Trichasterina");
addOption("Lyssacinosida-Rossellidae", "Vazella", "Vazella");
addOption("Lyssacinosida-Rossellidae", "NA", "NA");

addOption("Merliida", "Select Family", "None", "None", 1);
addList("Merliida", "Hamacanthidae", "Hamacanthidae", "Merliida-Hamacanthidae");
addList("Merliida", "Merliidae", "Merliidae", "Merliida-Merliidae");
addOption("Merliida-Hamacanthidae", "Select Genus", "None");
addOption("Merliida-Hamacanthidae", "Hamacantha", "Hamacantha");
addOption("Merliida-Merliidae", "Select Genus", "None");
addOption("Merliida-Merliidae", "Merlia", "Merlia");

addOption("Poecilosclerida", "Select Family", "None", "None", 1);
addList("Poecilosclerida", "Acarnidae", "Acarnidae", "Poecilosclerida-Acarnidae");
addList("Poecilosclerida", "Chondropsidae", "Chondropsidae", "Poecilosclerida-Chondropsidae");
addList("Poecilosclerida", "Cladorhizidae", "Cladorhizidae", "Poecilosclerida-Cladorhizidae");
addList("Poecilosclerida", "Coelosphaeridae", "Coelosphaeridae", "Poecilosclerida-Coelosphaeridae");
addList("Poecilosclerida", "Crambeidae", "Crambeidae", "Poecilosclerida-Crambeidae");
addList("Poecilosclerida", "Crellidae", "Crellidae", "Poecilosclerida-Crellidae");
addList("Poecilosclerida", "Dendoricellidae", "Dendoricellidae", "Poecilosclerida-Dendoricellidae");
addList("Poecilosclerida", "Desmacellidae", "Desmacellidae", "Poecilosclerida-Desmacellidae");
addList("Poecilosclerida", "Desmacididae", "Desmacididae", "Poecilosclerida-Desmacididae");
addList("Poecilosclerida", "Esperiopsidae", "Esperiopsidae", "Poecilosclerida-Esperiopsidae");
addList("Poecilosclerida", "Guitarridae", "Guitarridae", "Poecilosclerida-Guitarridae");
addList("Poecilosclerida", "Hymedesmiidae", "Hymedesmiidae", "Poecilosclerida-Hymedesmiidae");
addList("Poecilosclerida", "Iotrochotidae", "Iotrochotidae", "Poecilosclerida-Iotrochotidae");
addList("Poecilosclerida", "Isodictyidae", "Isodictyidae", "Poecilosclerida-Isodictyidae");
addList("Poecilosclerida", "Latrunculiidae", "Latrunculiidae", "Poecilosclerida-Latrunculiidae");
addList("Poecilosclerida", "Microcionidae", "Microcionidae", "Poecilosclerida-Microcionidae");
addList("Poecilosclerida", "Mycalidae", "Mycalidae", "Poecilosclerida-Mycalidae");
addList("Poecilosclerida", "Myxillidae", "Myxillidae", "Poecilosclerida-Myxillidae");
addList("Poecilosclerida", "Phellodermidae", "Phellodermidae", "Poecilosclerida-Phellodermidae");
addList("Poecilosclerida", "Podospongiidae", "Podospongiidae", "Poecilosclerida-Podospongiidae");
addList("Poecilosclerida", "Tedaniidae", "Tedaniidae", "Poecilosclerida-Tedaniidae");
addList("Poecilosclerida", "NA", "NA", "Poecilosclerida-NA");
addOption("Poecilosclerida-Acarnidae", "Select Genus", "None");
addOption("Poecilosclerida-Acarnidae", "Acarnus", "Acarnus");
addOption("Poecilosclerida-Acarnidae", "Cornulum", "Cornulum");
addOption("Poecilosclerida-Acarnidae", "Iophon", "Iophon");
addOption("Poecilosclerida-Acarnidae", "Megaciella", "Megaciella");
addOption("Poecilosclerida-Acarnidae", "Wigginsia", "Wigginsia");
addOption("Poecilosclerida-Acarnidae", "Zyzzya", "Zyzzya");
addOption("Poecilosclerida-Acarnidae", "NA", "NA");
addOption("Poecilosclerida-Chondropsidae", "Select Genus", "None");
addOption("Poecilosclerida-Chondropsidae", "Strongylacidon", "Strongylacidon");
addOption("Poecilosclerida-Cladorhizidae", "Select Genus", "None");
addOption("Poecilosclerida-Cladorhizidae", "Abyssocladia", "Abyssocladia");
addOption("Poecilosclerida-Cladorhizidae", "Asbestopluma", "Asbestopluma");
addOption("Poecilosclerida-Cladorhizidae", "Chondrocladia", "Chondrocladia");
addOption("Poecilosclerida-Cladorhizidae", "Cladorhiza", "Cladorhiza");
addOption("Poecilosclerida-Cladorhizidae", "Euchelipluma", "Euchelipluma");
addOption("Poecilosclerida-Cladorhizidae", "Lollipocladia", "Lollipocladia");
addOption("Poecilosclerida-Cladorhizidae", "NA", "NA");
addOption("Poecilosclerida-Coelosphaeridae", "Select Genus", "None");
addOption("Poecilosclerida-Coelosphaeridae", "Coelosphaera", "Coelosphaera");
addOption("Poecilosclerida-Coelosphaeridae", "Forcepia", "Forcepia");
addOption("Poecilosclerida-Coelosphaeridae", "Histodermella", "Histodermella");
addOption("Poecilosclerida-Coelosphaeridae", "Inflatella", "Inflatella");
addOption("Poecilosclerida-Coelosphaeridae", "Lissodendoryx", "Lissodendoryx");
addOption("Poecilosclerida-Coelosphaeridae", "NA", "NA");
addOption("Poecilosclerida-Crambeidae", "Select Genus", "None");
addOption("Poecilosclerida-Crambeidae", "Discorhabdella", "Discorhabdella");
addOption("Poecilosclerida-Crambeidae", "Monanchora", "Monanchora");
addOption("Poecilosclerida-Crambeidae", "NA", "NA");
addOption("Poecilosclerida-Crellidae", "Select Genus", "None");
addOption("Poecilosclerida-Crellidae", "Crella", "Crella");
addOption("Poecilosclerida-Crellidae", "NA", "NA");
addOption("Poecilosclerida-Dendoricellidae", "Select Genus", "None");
addOption("Poecilosclerida-Dendoricellidae", "Pyloderma", "Pyloderma");
addOption("Poecilosclerida-Desmacellidae", "Select Genus", "None");
addOption("Poecilosclerida-Desmacellidae", "Neofibularia", "Neofibularia");
addOption("Poecilosclerida-Desmacididae", "Select Genus", "None");
addOption("Poecilosclerida-Desmacididae", "Desmacidon", "Desmacidon");
addOption("Poecilosclerida-Desmacididae", "Desmapsamma", "Desmapsamma");
addOption("Poecilosclerida-Esperiopsidae", "Select Genus", "None");
addOption("Poecilosclerida-Esperiopsidae", "Amphilectus", "Amphilectus");
addOption("Poecilosclerida-Esperiopsidae", "Esperiopsis", "Esperiopsis");
addOption("Poecilosclerida-Esperiopsidae", "Semisuberites", "Semisuberites");
addOption("Poecilosclerida-Esperiopsidae", "NA", "NA");
addOption("Poecilosclerida-Guitarridae", "Select Genus", "None");
addOption("Poecilosclerida-Guitarridae", "Euchelipluma", "Euchelipluma");
addOption("Poecilosclerida-Guitarridae", "Guitarra", "Guitarra");
addOption("Poecilosclerida-Hymedesmiidae", "Select Genus", "None");
addOption("Poecilosclerida-Hymedesmiidae", "Hymedesmia", "Hymedesmia");
addOption("Poecilosclerida-Hymedesmiidae", "Phorbas", "Phorbas");
addOption("Poecilosclerida-Hymedesmiidae", "NA", "NA");
addOption("Poecilosclerida-Iotrochotidae", "Select Genus", "None");
addOption("Poecilosclerida-Iotrochotidae", "Iotrochota", "Iotrochota");
addOption("Poecilosclerida-Isodictyidae", "Select Genus", "None");
addOption("Poecilosclerida-Isodictyidae", "Isodictya", "Isodictya");
addOption("Poecilosclerida-Latrunculiidae", "Select Genus", "None");
addOption("Poecilosclerida-Latrunculiidae", "Latrunculia", "Latrunculia");
//addOption("Poecilosclerida-Latrunculiidae", "NA", "NA");
addOption("Poecilosclerida-Microcionidae", "Select Genus", "None");
addOption("Poecilosclerida-Microcionidae", "Antho", "Antho");
addOption("Poecilosclerida-Microcionidae", "Artemisina", "Artemisina");
addOption("Poecilosclerida-Microcionidae", "Clathria", "Clathria");
addOption("Poecilosclerida-Microcionidae", "Echinoclathria", "Echinoclathria");
addOption("Poecilosclerida-Microcionidae", "Pandaros", "Pandaros");
addOption("Poecilosclerida-Microcionidae", "NA", "NA");
addOption("Poecilosclerida-Mycalidae", "Select Genus", "None");
addOption("Poecilosclerida-Mycalidae", "Mycale", "Mycale");
addOption("Poecilosclerida-Mycalidae", "NA", "NA");
addOption("Poecilosclerida-Myxillidae", "Select Genus", "None");
addOption("Poecilosclerida-Myxillidae", "Melonanchora", "Melonanchora");
addOption("Poecilosclerida-Myxillidae", "Myxilla", "Myxilla");
addOption("Poecilosclerida-Myxillidae", "Stelodoryx", "Stelodoryx");
addOption("Poecilosclerida-Myxillidae", "NA", "NA");
addOption("Poecilosclerida-Phellodermidae", "Select Genus", "None");
addOption("Poecilosclerida-Phellodermidae", "Echinostylinos", "Echinostylinos");
addOption("Poecilosclerida-Podospongiidae", "Select Genus", "None");
addOption("Poecilosclerida-Podospongiidae", "Podospongia", "Podospongia");
addOption("Poecilosclerida-Tedaniidae", "Select Genus", "None");
addOption("Poecilosclerida-Tedaniidae", "Tedania", "Tedania");

addOption("Polymastiida", "Select Family", "None", "None", 1);
addList("Polymastiida", "Polymastiidae", "Polymastiidae", "Polymastiida-Polymastiidae");
addOption("Polymastiida-Polymastiidae", "Select Genus", "None");
addOption("Polymastiida-Polymastiidae", "Polymastia", "Polymastia");
addOption("Polymastiida-Polymastiidae", "Pseudotrachya", "Pseudotrachya");
//addOption("Polymastiida-Polymastiidae", "Quasillina", "Quasillina");
addOption("Polymastiida-Polymastiidae", "Radiella", "Radiella");
addOption("Polymastiida-Polymastiidae", "Ridleia", "Ridleia");
addOption("Polymastiida-Polymastiidae", "Tentorium", "Tentorium");
addOption("Polymastiida-Polymastiidae", "Weberella", "Weberella");
addOption("Polymastiida-Polymastiidae", "NA", "NA");

addOption("Sceptrulophora", "Select Family", "None", "None", 1);
addList("Sceptrulophora", "Aphrocallistidae", "Aphrocallistidae", "Sceptrulophora-Aphrocallistidae");
addList("Sceptrulophora", "Euretidae", "Euretidae", "Sceptrulophora-Euretidae");
addList("Sceptrulophora", "Farreidae", "Farreidae", "Sceptrulophora-Farreidae");
addList("Sceptrulophora", "Tretodictyidae", "Tretodictyidae", "Sceptrulophora-Tretodictyidae");
addOption("Sceptrulophora-Aphrocallistidae", "Select Genus", "None");
addOption("Sceptrulophora-Aphrocallistidae", "Aphrocallistes", "Aphrocallistes");
addOption("Sceptrulophora-Aphrocallistidae", "Heterochone", "Heterochone");
addOption("Sceptrulophora-Aphrocallistidae", "NA", "NA");
addOption("Sceptrulophora-Euretidae", "Select Genus", "None");
addOption("Sceptrulophora-Euretidae", "Chonelasma", "Chonelasma");
addOption("Sceptrulophora-Euretidae", "Eurete", "Eurete");
addOption("Sceptrulophora-Euretidae", "Lefroyella", "Lefroyella");
addOption("Sceptrulophora-Euretidae", "Verrucocoeloidea", "Verrucocoeloidea");
addOption("Sceptrulophora-Euretidae", "NA", "NA");
addOption("Sceptrulophora-Farreidae", "Select Genus", "None");
addOption("Sceptrulophora-Farreidae", "Farrea", "Farrea");
addOption("Sceptrulophora-Tretodictyidae", "Select Genus", "None");
addOption("Sceptrulophora-Tretodictyidae", "Hexactinella", "Hexactinella");
addOption("Sceptrulophora-Tretodictyidae", "Sclerothamnopsis", "Sclerothamnopsis");

addOption("Scopalinida", "Select Family", "None", "None", 1);
addList("Scopalinida", "Scopalinidae", "Scopalinidae", "Scopalinida-Scopalinidae");
addOption("Scopalinida-Scopalinidae", "Select Genus", "None");
addOption("Scopalinida-Scopalinidae", "Scopalina", "Scopalina");
addOption("Scopalinida-Scopalinidae", "Stylissa", "Stylissa");

addOption("Suberitida", "Select Family", "None", "None", 1);
addList("Suberitida", "Halichondriidae", "Halichondriidae", "Suberitida-Halichondriidae");
addList("Suberitida", "Stylocordylidae", "Stylocordylidae", "Suberitida-Stylocordylidae");
addList("Suberitida", "Suberitidae", "Suberitidae", "Suberitida-Suberitidae");
addOption("Suberitida-Halichondriidae", "Select Genus", "None");
addOption("Suberitida-Halichondriidae", "Aaptos", "Aaptos");
addOption("Suberitida-Halichondriidae", "Axinyssa", "Axinyssa");
addOption("Suberitida-Halichondriidae", "Ciocalapata", "Ciocalapata");
addOption("Suberitida-Halichondriidae", "Ciocalypta", "Ciocalypta");
addOption("Suberitida-Halichondriidae", "Epipolasis", "Epipolasis");
addOption("Suberitida-Halichondriidae", "Halichondria", "Halichondria");
addOption("Suberitida-Halichondriidae", "Hymeniacidon", "Hymeniacidon");
addOption("Suberitida-Halichondriidae", "Sarcomella", "Sarcomella");
addOption("Suberitida-Halichondriidae", "Spongosorites", "Spongosorites");
addOption("Suberitida-Halichondriidae", "Topsentia", "Topsentia");
addOption("Suberitida-Halichondriidae", "NA", "NA");
addOption("Suberitida-Stylocordylidae", "Select Genus", "None");
addOption("Suberitida-Stylocordylidae", "Stylocordyla", "Stylocordyla");
addOption("Suberitida-Suberitidae", "Select Genus", "None");
addOption("Suberitida-Suberitidae", "Aaptos", "Aaptos");
addOption("Suberitida-Suberitidae", "Homaxinella", "Homaxinella");
addOption("Suberitida-Suberitidae", "Pseudosuberites", "Pseudosuberites");
addOption("Suberitida-Suberitidae", "Rhizaxinella", "Rhizaxinella");
addOption("Suberitida-Suberitidae", "Suberites", "Suberites");
addOption("Suberitida-Suberitidae", "Terpios", "Terpios");

addOption("Tethyida", "Select Family", "None", "None", 1);
addList("Tethyida", "Tethyidae", "Tethyidae", "Tethyida-Tethyidae");
addList("Tethyida", "Timeidae", "Timeidae", "Tethyida-Timeidae");
addOption("Tethyida-Tethyidae", "Select Genus", "None");
addOption("Tethyida-Tethyidae", "Halicometes", "Halicometes");
addOption("Tethyida-Tethyidae", "Nucleotethya", "Nucleotethya");
addOption("Tethyida-Tethyidae", "Tectitethya", "Tectitethya");
addOption("Tethyida-Tethyidae", "Tethya", "Tethya");
addOption("Tethyida-Tethyidae", "NA", "NA");
addOption("Tethyida-Timeidae", "Select Genus", "None");
addOption("Tethyida-Timeidae", "Timea", "Timea");

addOption("Tetractinellida", "Select Family", "None", "None", 1);
addList("Tetractinellida", "Ancorinidae", "Ancorinidae", "Tetractinellida-Ancorinidae");
addList("Tetractinellida", "Azoricidae", "Azoricidae", "Tetractinellida-Azoricidae");
addList("Tetractinellida", "Calthropellidae", "Calthropellidae", "Tetractinellida-Calthropellidae");
addList("Tetractinellida", "Corallistidae", "Corallistidae", "Tetractinellida-Corallistidae");
addList("Tetractinellida", "Geodiidae", "Geodiidae", "Tetractinellida-Geodiidae");
addList("Tetractinellida", "Macandrewiidae", "Macandrewiidae", "Tetractinellida-Macandrewiidae");
addList("Tetractinellida", "Neopeltidae", "Neopeltidae", "Tetractinellida-Neopeltidae");
addList("Tetractinellida", "Pachastrellidae", "Pachastrellidae", "Tetractinellida-Pachastrellidae");
addList("Tetractinellida", "Scleritodermidae", "Scleritodermidae", "Tetractinellida-Scleritodermidae");
addList("Tetractinellida", "Siphonidiidae", "Siphonidiidae", "Tetractinellida-Siphonidiidae");
addList("Tetractinellida", "Tetillidae", "Tetillidae", "Tetractinellida-Tetillidae");
addList("Tetractinellida", "Theneidae", "Theneidae", "Tetractinellida-Theneidae");
addList("Tetractinellida", "Theonellidae", "Theonellidae", "Tetractinellida-Theonellidae");
addList("Tetractinellida", "Thrombidae", "Thrombidae", "Tetractinellida-Thrombidae");
addList("Tetractinellida", "Vulcanellidae", "Vulcanellidae", "Tetractinellida-Vulcanellidae");
addList("Tetractinellida", "NA", "NA", "Tetractinellida-NA");
addOption("Tetractinellida-Ancorinidae", "Select Genus", "None");
addOption("Tetractinellida-Ancorinidae", "Ancorina", "Ancorina");
addOption("Tetractinellida-Ancorinidae", "Asteropus", "Asteropus");
addOption("Tetractinellida-Ancorinidae", "Dercitus", "Dercitus");
addOption("Tetractinellida-Ancorinidae", "Ecionemia", "Ecionemia");
addOption("Tetractinellida-Ancorinidae", "Jaspis", "Jaspis");
addOption("Tetractinellida-Ancorinidae", "Stelletta", "Stelletta");
addOption("Tetractinellida-Ancorinidae", "Stellettinopsis", "Stellettinopsis");
addOption("Tetractinellida-Ancorinidae", "Stryphnus", "Stryphnus");
addOption("Tetractinellida-Ancorinidae", "Tribrachium", "Tribrachium");
addOption("Tetractinellida-Ancorinidae", "NA", "NA");
addOption("Tetractinellida-Azoricidae", "Select Genus", "None");
addOption("Tetractinellida-Azoricidae", "Desmascula", "Desmascula");
addOption("Tetractinellida-Azoricidae", "Leiodermatium", "Leiodermatium");
addOption("Tetractinellida-Calthropellidae", "Select Genus", "None");
addOption("Tetractinellida-Calthropellidae", "Calthropella", "Calthropella");
addOption("Tetractinellida-Calthropellidae", "NA", "NA");
addOption("Tetractinellida-Corallistidae", "Select Genus", "None");
addOption("Tetractinellida-Corallistidae", "Corallistes", "Corallistes");
addOption("Tetractinellida-Corallistidae", "NA", "NA");
addOption("Tetractinellida-Geodiidae", "Select Genus", "None");
addOption("Tetractinellida-Geodiidae", "Erylus", "Erylus");
addOption("Tetractinellida-Geodiidae", "Geodia", "Geodia");
addOption("Tetractinellida-Geodiidae", "Penares", "Penares");
addOption("Tetractinellida-Geodiidae", "NA", "NA");
addOption("Tetractinellida-Macandrewiidae", "Select Genus", "None");
addOption("Tetractinellida-Macandrewiidae", "Macandrewia", "Macandrewia");
addOption("Tetractinellida-Neopeltidae", "Select Genus", "None");
addOption("Tetractinellida-Neopeltidae", "Neopelta", "Neopelta");
addOption("Tetractinellida-Pachastrellidae", "Select Genus", "None");
addOption("Tetractinellida-Pachastrellidae", "Brachiaster", "Brachiaster");
addOption("Tetractinellida-Pachastrellidae", "Characella", "Characella");
addOption("Tetractinellida-Pachastrellidae", "Pachastrella", "Pachastrella");
addOption("Tetractinellida-Pachastrellidae", "Poecillastra", "Poecillastra");
addOption("Tetractinellida-Pachastrellidae", "NA", "NA");
addOption("Tetractinellida-Scleritodermidae", "Select Genus", "None");
addOption("Tetractinellida-Scleritodermidae", "Aciculites", "Aciculites");
addOption("Tetractinellida-Scleritodermidae", "Setidium", "Setidium");
addOption("Tetractinellida-Siphonidiidae", "Select Genus", "None");
addOption("Tetractinellida-Siphonidiidae", "Gastrophanella", "Gastrophanella");
addOption("Tetractinellida-Siphonidiidae", "Siphonidium", "Siphonidium");
addOption("Tetractinellida-Siphonidiidae", "NA", "NA");
addOption("Tetractinellida-Tetillidae", "Select Genus", "None");
addOption("Tetractinellida-Tetillidae", "Cinachyra", "Cinachyra");
addOption("Tetractinellida-Tetillidae", "Cinachyrella", "Cinachyrella");
addOption("Tetractinellida-Tetillidae", "Craniella", "Craniella");
addOption("Tetractinellida-Tetillidae", "Fangophilina", "Fangophilina");
addOption("Tetractinellida-Tetillidae", "Tetilla", "Tetilla");
addOption("Tetractinellida-Theneidae", "Select Genus", "None");
addOption("Tetractinellida-Theneidae", "Thenea", "Thenea");
addOption("Tetractinellida-Theneidae", "NA", "NA");
addOption("Tetractinellida-Theonellidae", "Select Genus", "None");
addOption("Tetractinellida-Theonellidae", "Discodermia", "Discodermia");
addOption("Tetractinellida-Theonellidae", "Racodiscula", "Racodiscula");
addOption("Tetractinellida-Theonellidae", "Theonella", "Theonella");
addOption("Tetractinellida-Thrombidae", "Select Genus", "None");
addOption("Tetractinellida-Thrombidae", "Thrombus", "Thrombus");
addOption("Tetractinellida-Thrombidae", "Yucatania", "Yucatania");
addOption("Tetractinellida-Vulcanellidae", "Select Genus", "None");
addOption("Tetractinellida-Vulcanellidae", "Poecillastra", "Poecillastra");
addOption("Tetractinellida-Vulcanellidae", "Vulcanella", "Vulcanella");
addOption("Tetractinellida-Vulcanellidae", "NA", "NA");

addOption("Verongiida", "Select Family", "None", "None", 1);
addList("Verongiida", "Aplysinidae", "Aplysinidae", "Verongiida-Aplysinidae");
addList("Verongiida", "Ianthellidae", "Ianthellidae", "Verongiida-Ianthellidae");
addList("Verongiida", "NA", "NA", "Verongiida-NA");
addOption("Verongiida-Aplysinidae", "Select Genus", "None");
addOption("Verongiida-Aplysinidae", "Aiolochroia", "Aiolochroia");
addOption("Verongiida-Aplysinidae", "Aplysina", "Aplysina");
addOption("Verongiida-Aplysinidae", "Verongula", "Verongula");
addOption("Verongiida-Aplysinidae", "NA", "NA");
addOption("Verongiida-Ianthellidae", "Select Genus", "None");
addOption("Verongiida-Ianthellidae", "Ianthella", "Ianthella");